import { expect, type APIRequestContext, type APIResponse, type Page } from "@playwright/test";
export const uatBaseUrl=process.env.UAT_BASE_URL??"https://terry4410.github.io/field-visit-mileage-system/";
export const apiBaseUrl=process.env.UAT_API_BASE_URL??"https://api-fieldvisit-uat-cxauf4g8fzdyfsd9.eastasia-01.azurewebsites.net";
export const demoPassword=process.env.UAT_DEMO_PASSWORD??"";
export function auth(token:string,role?:string){return{Authorization:`Bearer ${token}`,...(role?{"X-Active-Role":role}:{})};}
export async function ok(r:APIResponse,label:string){if(r.ok())return;throw new Error(`${label}: HTTP ${r.status()} - ${await r.text()}`);}
export async function login(request:APIRequestContext,account:string){if(!demoPassword)throw new Error("UAT_DEMO_PASSWORD is required for Internal Business UAT.");const r=await request.post(`${apiBaseUrl}/api/v1/auth/demo-login`,{data:{account,password:demoPassword}});await ok(r,`login ${account}`);return await r.json();}
export async function loginUi(page:Page,account:string,title:string){if(!demoPassword)throw new Error("UAT_DEMO_PASSWORD is required for Internal Business UAT.");await page.goto(uatBaseUrl,{waitUntil:"domcontentloaded"});const c=page.locator(".login-card");await expect(c).toBeVisible();await c.locator("input").nth(0).fill(account);await c.locator('input[type="password"]').fill(demoPassword);await c.getByRole("button",{name:"登入",exact:true}).click();await expect(page.locator(".topbar h1")).toHaveText(title);}
export function unique(label:string){return`UAT-AUTO-${label}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}
export function today(){const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());return`${p.find(x=>x.type==="year")!.value}-${p.find(x=>x.type==="month")!.value}-${p.find(x=>x.type==="day")!.value}`;}
export function addDays(s:string,n:number){const d=new Date(`${s}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export async function teamId(v:any){const scopes=Array.isArray(v.user.teamScopes)?v.user.teamScopes:[];const primary=scopes.find((x:any)=>x.isPrimary)?.teamId??null;const id=primary??(scopes.length===0?v.user.teamId:null);if(!id)throw new Error(`${v.user.employeeNo??"pilotv01"} has no active/primary team`);return id;}\nexport function assertLeaderTeamScope(l:any,tid:number){const scopes=Array.isArray(l.user.teamScopes)?l.user.teamScopes:[];const ids=scopes.length>0?scopes.map((x:any)=>x.teamId):(l.user.teamId?[l.user.teamId]:[]);if(!ids.includes(tid))throw new Error(`${l.user.employeeNo??"pilotl01"} is not authorized for visitor team ${tid}`);}
export async function locations(request:APIRequestContext,v:any,tid:number){const r=await request.get(`${apiBaseUrl}/api/v1/locations`,{headers:auth(v.accessToken,"visitor")});await ok(r,"locations");return(await r.json()).filter((x:any)=>x.isActive&&x.approvalStatus==="Approved"&&(x.teamId===null||x.teamId===tid));}
export async function rates(request:APIRequestContext,token:string,role:string){const r=await request.get(`${apiBaseUrl}/api/v1/mileage-rate-rules`,{headers:auth(token,role)});await ok(r,"rates");return await r.json();}
export async function slot(request:APIRequestContext,v:any,rs:any[]){const t=today(),active=rs.filter(x=>x.isActive&&x.vehicleType.toLowerCase()==="motorcycle"&&(!x.effectiveTo||x.effectiveTo>=t)).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom)),times=[["08:05:00","08:35:00"],["09:05:00","09:35:00"],["10:05:00","10:35:00"],["13:05:00","13:35:00"],["14:05:00","14:35:00"],["15:05:00","15:35:00"]];for(const rate of active){const first=rate.effectiveFrom>addDays(t,14)?rate.effectiveFrom:addDays(t,14);for(let d=0;d<45;d++){const visitDate=addDays(first,d);if(rate.effectiveTo&&visitDate>rate.effectiveTo)break;for(const [startTime,endTime]of times){const r=await request.post(`${apiBaseUrl}/api/v1/trips/time-overlap-check`,{headers:auth(v.accessToken,"visitor"),data:{visitDate,startTime,endTime,excludeVisitTripId:null}});await ok(r,"overlap");if(!(await r.json()).hasOverlap)return{visitDate,startTime,endTime};}}}throw new Error("No safe rated slot");}
export function stop(l:any,projectId:number|null=null,visitTypeId:number|null=null){return{locationId:l.locationId,projectId,visitTypeId,sourceType:"Master",locationName:l.locationName,address:l.address,visitPurpose:"UAT-AUTO-business-dry-run",notes:null};}
export async function createTrip(request:APIRequestContext,v:any,tid:number,purpose:string,s:any,stops:any[],km:number|null,notes=purpose){const r=await request.post(`${apiBaseUrl}/api/v1/trips`,{headers:auth(v.accessToken,"visitor"),data:{visitDate:s.visitDate,startTime:s.startTime,endTime:s.endTime,claimedDistanceKm:km,purpose,notes,timeOverlapConfirmed:false,teamId:tid,stops}});await ok(r,"create trip");return await r.json();}
export async function submit(request:APIRequestContext,v:any,t:any){const r=await request.post(`${apiBaseUrl}/api/v1/trips/${t.visitTripId}/submit`,{headers:{...auth(v.accessToken,"visitor"),"If-Match":t.rowVersion},data:{confirmTimeOverlap:false}});await ok(r,"submit trip");return await r.json();}
export async function job(request:APIRequestContext,l:any,tripId:number){const r=await request.post(`${apiBaseUrl}/api/v1/jobs/mileage`,{headers:auth(l.accessToken,"leader"),data:{mode:"Selected",startDate:null,endDate:null,selectedTripIds:[tripId]}});await ok(r,"enqueue mileage");const j=await r.json();for(let i=0;i<60;i++){const p=await request.get(`${apiBaseUrl}/api/v1/jobs/${j.backgroundJobId}`,{headers:auth(l.accessToken,"leader")});await ok(p,"poll mileage");const x=await p.json();if(["Succeeded","PartiallySucceeded","Failed"].includes(x.status)){expect(x.status).toBe("Succeeded");expect(x.totalCount).toBe(1);expect(x.successCount).toBe(1);return j.backgroundJobId;}await new Promise(z=>setTimeout(z,500));}throw new Error("Mileage job timeout");}
export async function approve(request:APIRequestContext,l:any,id:number){const g=await request.get(`${apiBaseUrl}/api/v1/trips/${id}`,{headers:auth(l.accessToken,"leader")});await ok(g,"load pending");const t=await g.json();expect(t.status).toBe("PendingApproval");const r=await request.post(`${apiBaseUrl}/api/v1/trips/${id}/approve`,{headers:auth(l.accessToken,"leader"),data:{approvedDistanceKm:t.systemDistanceKm,rowVersion:t.rowVersion,comments:"UAT-AUTO approval"}});await ok(r,"approve");return await r.json();}
export async function approvedTrip(request:APIRequestContext,v:any,l:any,tid:number,purpose:string,s:any,stops:any[]){const d=await createTrip(request,v,tid,purpose,s,stops,10,purpose);await submit(request,v,d);const backgroundJobId=await job(request,l,d.visitTripId);const trip=await approve(request,l,d.visitTripId);expect(trip.status).toBe("Approved");return{trip,backgroundJobId};}
export async function cleanup(request:APIRequestContext,a:any,id:number|null,purpose:string,backgroundJobId:string|null=null){if(id===null)return;const r=await request.post(`${apiBaseUrl}/api/v1/uat-automation/cleanup-trip`,{headers:{...auth(a.accessToken,"admin"),"X-UAT-Automation-Key":demoPassword},data:{visitTripId:id,expectedPurpose:purpose,backgroundJobId}});await ok(r,"cleanup trip");expect((await r.json()).tripsDeleted).toBe(1);}
export async function query(request:APIRequestContext,token:string,role:string,p:any){const q=new URLSearchParams();for(const[k,v]of Object.entries(p))if(v!==null&&v!==undefined&&v!=="")q.set(k,String(v));q.set("page",q.get("page")??"1");q.set("pageSize",q.get("pageSize")??"100");const r=await request.get(`${apiBaseUrl}/api/v1/query/trips?${q}`,{headers:auth(token,role)});await ok(r,"query trips");return await r.json();}
export async function exportsOk(request:APIRequestContext,token:string,role:string,p:any){const q=new URLSearchParams(Object.entries(p).map(([k,v])=>[k,String(v)]));const x=await request.get(`${apiBaseUrl}/api/v1/query/trips/export.xlsx?${q}`,{headers:auth(token,role)});await ok(x,"xlsx");expect((x.headers()["content-type"]??"").toLowerCase()).toContain("spreadsheetml");const xb=await x.body();expect(xb.length).toBeGreaterThan(100);expect(Array.from(xb.subarray(0,2))).toEqual([0x50,0x4b]);const p1=await request.get(`${apiBaseUrl}/api/v1/query/trips/export.pdf?${q}`,{headers:auth(token,role)});await ok(p1,"pdf");expect((p1.headers()["content-type"]??"").toLowerCase()).toContain("pdf");const pb=await p1.body();expect(pb.length).toBeGreaterThan(100);expect(pb.subarray(0,5).toString("utf8")).toBe("%PDF-");}
export async function setup(request:APIRequestContext){const visitor=await login(request,"pilotv01"),leader=await login(request,"pilotl01"),admin=await login(request,"pilota01"),supervisor=await login(request,"pilots02"),tid=await teamId(visitor);assertLeaderTeamScope(leader,tid);const locs=await locations(request,visitor,tid);expect(locs.length).toBeGreaterThanOrEqual(2);const rs=await rates(request,visitor.accessToken,"visitor"),s=await slot(request,visitor,rs);return{visitor,leader,admin,supervisor,tid,locs,rs,s};}
export async function findLocation(request:APIRequestContext,a:any,q:string){const r=await request.get(`${apiBaseUrl}/api/v1/managed-locations/search?q=${encodeURIComponent(q)}&page=1&pageSize=100`,{headers:auth(a.accessToken,"admin")});await ok(r,"search managed location");return(await r.json()).items.find((x:any)=>x.locationName===q||x.locationCode===q)??null;}
export async function deleteLocation(request:APIRequestContext,a:any,id:number){const i=await request.get(`${apiBaseUrl}/api/v1/managed-locations/${id}/delete-impact`,{headers:auth(a.accessToken,"admin")});await ok(i,"location impact");const b=await i.json();expect(b.canDelete,b.reason??"cannot delete").toBe(true);const d=await request.delete(`${apiBaseUrl}/api/v1/managed-locations/${id}/permanent`,{headers:auth(a.accessToken,"admin")});await ok(d,"delete location");}
