import{useState}from"react";
import{api,apiDownload}from"../api";
import type{ImportConfirmResult,ImportPreview}from"../types";

export default function AdminImportPanel({type,onDone}:{type:"locations"|"projects";onDone:()=>void}){
 const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<ImportPreview|null>(null),[result,setResult]=useState<ImportConfirmResult|null>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const template=()=>apiDownload(`/imports/${type}/template`,type==="locations"?"地點主檔匯入範例.xlsx":"專案主檔匯入範例.xlsx");
 const doPreview=async()=>{if(!file)return setMsg("請先選擇 .xlsx、.xls 或 .csv 檔案。");setBusy(true);setMsg("");try{const form=new FormData();form.append("file",file);setPreview(await api<ImportPreview>(`/imports/${type}/preview`,{method:"POST",body:form},120000));setResult(null)}catch(e){setMsg(e instanceof Error?e.message:"預覽失敗")}finally{setBusy(false)}};
 const confirm=async()=>{if(!preview)return;setBusy(true);try{const r=await api<ImportConfirmResult>(`/imports/${preview.importBatchId}/confirm`,{method:"POST"},120000);setResult(r);setMsg("匯入完成。");onDone()}catch(e){setMsg(e instanceof Error?e.message:"匯入失敗")}finally{setBusy(false)}};
 return <div className="import-panel"><div className="section-title"><strong>批次匯入</strong><button className="btn small outline" onClick={()=>void template()}>下載 Excel 範例</button></div><div className="actions"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/><button className="btn secondary" disabled={busy} onClick={()=>void doPreview()}>預覽與驗證</button></div>{msg&&<div className="note">{msg}</div>}{preview&&<><div className={`note ${preview.errorCount?"danger-note":"ok-note"}`}>共 {preview.totalCount} 列｜可匯入 {preview.validCount}｜錯誤 {preview.errorCount}{preview.totalCount>100?"｜畫面僅顯示前 100 筆預覽，系統已驗證全部資料":""}</div><div className="table-wrap compact-table"><table><thead><tr><th>列</th><th>類型</th><th>動作</th><th>Key</th><th>結果</th></tr></thead><tbody>{preview.items.slice(0,100).map((x,i)=><tr key={i}><td>{x.rowNumber}</td><td>{x.entityType}</td><td>{x.action}</td><td>{x.displayKey}</td><td>{x.errorMessage||"OK"}</td></tr>)}</tbody></table></div><div className="actions">{preview.errorCount>0&&<button className="btn outline" onClick={()=>void apiDownload(`/imports/${preview.importBatchId}/errors.xlsx`,"匯入錯誤.xlsx")}>下載錯誤 Excel</button>}<button className="btn ok" disabled={preview.errorCount>0||busy} onClick={()=>void confirm()}>確認匯入</button></div></>}{result&&<div className="note ok-note">新增 {result.created}／更新 {result.updated}／無變更 {result.unchanged}／失敗 {result.failed}</div>}</div>
}
