import{useEffect,useState}from"react";
import{ApiError,api}from"../api";
import{useModalScrollLock}from"../use-modal-scroll-lock";
import type{ManagedLocationGovernanceCandidate,ManagedLocationGovernanceCandidatePage,ManagedLocationGovernanceDetail}from"../location-governance";

type Props={locationId:number;onClose:()=>void;onSaved:()=>void|Promise<void>};

export default function LocationGovernanceModal({locationId,onClose,onSaved}:Props){
 useModalScrollLock();
 const[detail,setDetail]=useState<ManagedLocationGovernanceDetail|null>(null),[taxId,setTaxId]=useState(''),[masterNote,setMasterNote]=useState(''),[duplicateId,setDuplicateId]=useState<number|null>(null),[reason,setReason]=useState('');
 const[q,setQ]=useState(''),[candidates,setCandidates]=useState<ManagedLocationGovernanceCandidate[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const apply=(x:ManagedLocationGovernanceDetail)=>{setDetail(x);setTaxId(x.taxId||'');setMasterNote(x.masterNote||'');setDuplicateId(x.duplicateOfLocationId??null);setReason(x.duplicateReason||'')};
 const loadDetail=async()=>apply(await api<ManagedLocationGovernanceDetail>(`/managed-locations/${locationId}/governance`));
 const loadCandidates=async(value=q)=>{const p=new URLSearchParams({locationId:String(locationId),page:'1',pageSize:'20'});if(value.trim())p.set('q',value.trim());const r=await api<ManagedLocationGovernanceCandidatePage>(`/managed-locations/governance-candidates?${p}`);setCandidates(r.items)};
 useEffect(()=>{void loadDetail().catch(e=>setNotice(e instanceof Error?e.message:'讀取治理資料失敗'));void loadCandidates('').catch(e=>setNotice(e instanceof Error?e.message:'讀取候選地點失敗'))},[locationId]);
 const clearDuplicate=()=>{setDuplicateId(null);setReason('')};
 const save=async()=>{if(!detail)return;if(duplicateId&&!reason.trim()){setNotice('設定疑似重複地點參考時必須填寫原因。');return}setBusy(true);setNotice('');try{await api(`/managed-locations/${locationId}/governance`,{method:'PUT',body:JSON.stringify({taxId:taxId||null,masterNote:masterNote||null,duplicateOfLocationId:duplicateId,duplicateReason:duplicateId?reason:null,rowVersion:detail.rowVersion})});await onSaved()}catch(e){if(e instanceof ApiError&&e.status===409){setNotice('此地點已被其他人更新，本次變更未儲存。');try{await loadDetail();setNotice('此地點已被其他人更新，本次變更未儲存。最新資料已重新載入，請重新確認後再儲存。')}catch(reload){setNotice(reload instanceof Error?reload.message:'重新載入最新資料失敗')}return}setNotice(e instanceof Error?e.message:'儲存失敗')}finally{setBusy(false)}};
 return <div className="modal"><div className="modal-panel" role="dialog" aria-modal="true" aria-label="Location Governance" style={{maxHeight:'86vh',overflowY:'auto'}}><button className="btn small outline modal-close" aria-label="關閉地點治理視窗" disabled={busy} onClick={onClose}>關閉</button><h3>Location Governance｜地點治理</h3>{notice&&<div role="alert" className="note">{notice}</div>}{!detail?<div className="sub">載入中…</div>:<><div className="grid cols-2"><div className="field"><label>地點代碼</label><div>{detail.locationCode||'—'}</div></div><div className="field"><label>地點名稱</label><div>{detail.locationName}</div></div><div className="field span-2"><label>地址</label><div>{detail.address||'—'}</div></div><div className="field span-2"><label>統編／稅籍識別（查詢參考，可重複）</label><input value={taxId} onChange={e=>setTaxId(e.target.value)}/></div><div className="field span-2"><label>主檔治理備註</label><textarea value={masterNote} onChange={e=>setMasterNote(e.target.value)} rows={3}/></div></div><h4>疑似重複地點參考</h4><div className="actions"><input aria-label="搜尋疑似重複地點" value={q} placeholder="代碼／名稱／地址／統編" onChange={e=>setQ(e.target.value)}/><button className="btn small secondary" disabled={busy} onClick={()=>void loadCandidates()}>搜尋</button>{duplicateId&&<button className="btn small outline" disabled={busy} onClick={clearDuplicate}>清除參考</button>}</div><div className="route-list" style={{maxHeight:220,overflowY:'auto'}}>{candidates.map(c=><label className="route-item" key={c.locationId}><input type="radio" name="duplicate-location" checked={duplicateId===c.locationId} onChange={()=>setDuplicateId(c.locationId)}/><div><div className="route-name">{c.locationCode}｜{c.locationName}</div><div className="route-address">{c.address||'—'}{c.taxId?`｜統編 ${c.taxId}`:''}｜{c.isActive?'啟用':'停用'}</div></div></label>)}</div>{duplicateId&&<div className="field"><label>重複參考原因</label><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></div>}<div className="modal-sticky-actions"><button className="btn secondary" disabled={busy} onClick={onClose}>取消</button><button className="btn ok" disabled={busy||!!duplicateId&&!reason.trim()} onClick={()=>void save()}>儲存治理資料</button></div></>}</div></div>
}
