using FieldVisit.Application;
using FieldVisit.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace FieldVisit.Infrastructure;

public sealed class V180MasterDataAdminRepository(AppDbContext db) : IV180MasterDataAdminRepository
{
    public async Task<V180MasterDataReadinessDto> GetReadinessAsync(CurrentUserDto admin, CancellationToken ct)
    {
        var org=Org(admin); var today=BusinessTime.Today;
        var employmentStatusMissing=await db.Employments.CountAsync(x=>x.OrganizationId==org&&!db.EmploymentStatusPeriods.Any(s=>s.EmploymentId==x.EmploymentId&&s.EffectiveFrom<=today&&(!s.EffectiveTo.HasValue||today<=s.EffectiveTo)),ct);
        var teamCenterMissing=await db.Teams.CountAsync(x=>x.OrganizationId==org&&x.IsActive&&!db.TeamMemberships.Any(m=>m.TeamId==x.TeamId),ct); // surfaced as a conservative readiness warning
        var sites=await db.DeploymentSites.CountAsync(x=>db.Centers.Any(c=>c.CenterId==x.CenterId&&c.OrganizationId==org),ct);
        var teamSiteMissing=await db.TeamMemberships.Where(m=>db.Employments.Any(e=>e.EmploymentId==m.EmploymentId&&e.OrganizationId==org)).Select(m=>m.TeamId).Distinct().CountAsync(t=>!db.TeamDeploymentSiteAssignments.Any(x=>x.TeamId==t&&x.EffectiveFrom<=today&&(!x.EffectiveTo.HasValue||today<=x.EffectiveTo)),ct);
        var employmentSiteMissing=await db.Employments.CountAsync(e=>e.OrganizationId==org&&!db.EmploymentDeploymentSiteAssignments.Any(x=>x.EmploymentId==e.EmploymentId&&x.EffectiveFrom<=today&&(!x.EffectiveTo.HasValue||today<=x.EffectiveTo)),ct);
        return new(employmentStatusMissing,teamCenterMissing,sites,teamSiteMissing,employmentSiteMissing,employmentStatusMissing==0&&teamCenterMissing==0&&sites>0&&teamSiteMissing==0&&employmentSiteMissing==0);
    }

    public async Task<IReadOnlyList<V180MasterDataRow>> ListAsync(CurrentUserDto a,string kind,CancellationToken ct)
    {
        var org=Org(a); kind=kind.Trim().ToLowerInvariant();
        return kind switch
        {
            "employment-status" => await (from x in db.EmploymentStatusPeriods join e in db.Employments on x.EmploymentId equals e.EmploymentId where e.OrganizationId==org select new V180MasterDataRow(x.EmploymentStatusPeriodId,e.EmployeeNo??"",x.EmploymentStatus,x.EmploymentStatus,x.EffectiveFrom,x.EffectiveTo,null,null,B64(x.RowVersion))).ToListAsync(ct),
            "centers" => await db.Centers.Where(x=>x.OrganizationId==org).Select(x=>new V180MasterDataRow(x.CenterId,x.CenterCode,null,x.CenterName,x.EffectiveFrom,x.EffectiveTo,x.IsActive,null,B64(x.RowVersion))).ToListAsync(ct),
            "team-centers" => await (from x in db.Set<TeamCenterAssignment>() join t in db.Teams on x.TeamId equals t.TeamId join c in db.Centers on x.CenterId equals c.CenterId where t.OrganizationId==org select new V180MasterDataRow(x.TeamCenterAssignmentId,t.TeamCode,c.CenterCode,null,x.EffectiveFrom,x.EffectiveTo,null,null,B64(x.RowVersion))).ToListAsync(ct),
            "deployment-sites" => await (from x in db.DeploymentSites join c in db.Centers on x.CenterId equals c.CenterId where c.OrganizationId==org select new V180MasterDataRow(x.DeploymentSiteId,x.SiteCode,c.CenterCode,x.SiteName,x.EffectiveFrom,x.EffectiveTo,x.IsActive,null,B64(x.RowVersion))).ToListAsync(ct),
            "team-sites" => await (from x in db.TeamDeploymentSiteAssignments join t in db.Teams on x.TeamId equals t.TeamId join s in db.DeploymentSites on x.DeploymentSiteId equals s.DeploymentSiteId join c in db.Centers on s.CenterId equals c.CenterId where c.OrganizationId==org select new V180MasterDataRow(x.TeamDeploymentSiteAssignmentId,t.TeamCode,s.SiteCode,null,x.EffectiveFrom,x.EffectiveTo,null,null,B64(x.RowVersion))).ToListAsync(ct),
            "employment-sites" => await (from x in db.EmploymentDeploymentSiteAssignments join e in db.Employments on x.EmploymentId equals e.EmploymentId join s in db.DeploymentSites on x.DeploymentSiteId equals s.DeploymentSiteId join c in db.Centers on s.CenterId equals c.CenterId where c.OrganizationId==org select new V180MasterDataRow(x.EmploymentDeploymentSiteAssignmentId,e.EmployeeNo??"",s.SiteCode,null,x.EffectiveFrom,x.EffectiveTo,null,x.IsPrimary,B64(x.RowVersion))).ToListAsync(ct),
            _ => throw new InvalidOperationException("UNKNOWN_MASTER_DATA_TYPE")
        };
    }

    public async Task<V180MasterDataRow> SaveEmploymentStatusAsync(CurrentUserDto a,long? id,V180EmploymentStatusInput x,CancellationToken ct)
    { V180MasterDataValidationService.Period(x.EffectiveFrom,x.EffectiveTo); V180MasterDataValidationService.Status(x.Status); var e=await Employment(a,x.EmployeeNo,ct); var q=db.EmploymentStatusPeriods.Where(z=>z.EmploymentId==e.EmploymentId); if(await q.AnyAsync(z=>(!id.HasValue||z.EmploymentStatusPeriodId!=id)&&V180MasterDataValidationService.Overlaps(x.EffectiveFrom,x.EffectiveTo,z.EffectiveFrom,z.EffectiveTo),ct)) throw new InvalidOperationException("OVERLAPPING_EMPLOYMENT_STATUS"); var r=id.HasValue?await q.SingleAsync(z=>z.EmploymentStatusPeriodId==id,ct):new EmploymentStatusPeriod{EmploymentId=e.EmploymentId}; if(id.HasValue)V180MasterDataValidationService.RowVersion(x.RowVersion,r.RowVersion); r.EmploymentStatus=x.Status.Trim();r.EffectiveFrom=x.EffectiveFrom;r.EffectiveTo=x.EffectiveTo;r.SourceType="UAT-Admin";if(!id.HasValue)db.EmploymentStatusPeriods.Add(r); await SaveAudit(a,"EmploymentStatusPeriod",r.EmploymentStatusPeriodId.ToString(),id.HasValue?"Update":"Create",ct);await db.SaveChangesAsync(ct);return new(r.EmploymentStatusPeriodId,e.EmployeeNo??"",r.EmploymentStatus,r.EmploymentStatus,r.EffectiveFrom,r.EffectiveTo,null,null,B64(r.RowVersion)); }

    public async Task<V180MasterDataRow> SaveCenterAsync(CurrentUserDto a,int? id,V180CenterInput x,CancellationToken ct)
    { V180MasterDataValidationService.Period(x.EffectiveFrom,x.EffectiveTo);var org=Org(a);var r=id.HasValue?await db.Centers.SingleAsync(z=>z.CenterId==id&&z.OrganizationId==org,ct):new Center{OrganizationId=org};if(id.HasValue)V180MasterDataValidationService.RowVersion(x.RowVersion,r.RowVersion);if(await db.Centers.AnyAsync(z=>z.OrganizationId==org&&z.CenterCode==x.CenterCode&&z.CenterId!=r.CenterId,ct))throw new InvalidOperationException("DUPLICATE_CENTER_CODE");r.CenterCode=x.CenterCode.Trim();r.CenterName=x.CenterName.Trim();r.EffectiveFrom=x.EffectiveFrom;r.EffectiveTo=x.EffectiveTo;r.IsActive=x.IsActive;if(!id.HasValue)db.Centers.Add(r);await SaveAudit(a,"Center",r.CenterCode,id.HasValue?"Update":"Create",ct);await db.SaveChangesAsync(ct);return new(r.CenterId,r.CenterCode,null,r.CenterName,r.EffectiveFrom,r.EffectiveTo,r.IsActive,null,B64(r.RowVersion)); }

    public async Task<V180MasterDataRow> SaveTeamCenterAsync(CurrentUserDto a,long? id,V180TeamCenterInput x,CancellationToken ct)
    { V180MasterDataValidationService.Period(x.EffectiveFrom,x.EffectiveTo);var t=await Team(a,x.TeamCode,ct);var c=await Center(a,x.CenterCode,ct);var q=db.Set<TeamCenterAssignment>().Where(z=>z.TeamId==t.TeamId);if(await q.AnyAsync(z=>(!id.HasValue||z.TeamCenterAssignmentId!=id)&&V180MasterDataValidationService.Overlaps(x.EffectiveFrom,x.EffectiveTo,z.EffectiveFrom,z.EffectiveTo),ct))throw new InvalidOperationException("OVERLAPPING_TEAM_CENTER");var r=id.HasValue?await q.SingleAsync(z=>z.TeamCenterAssignmentId==id,ct):new TeamCenterAssignment{TeamId=t.TeamId};if(id.HasValue)V180MasterDataValidationService.RowVersion(x.RowVersion,r.RowVersion);r.CenterId=c.CenterId;r.EffectiveFrom=x.EffectiveFrom;r.EffectiveTo=x.EffectiveTo;if(!id.HasValue)db.Add(r);await SaveAudit(a,"TeamCenterAssignment",r.TeamCenterAssignmentId.ToString(),id.HasValue?"Update":"Create",ct);await db.SaveChangesAsync(ct);return new(r.TeamCenterAssignmentId,t.TeamCode,c.CenterCode,null,r.EffectiveFrom,r.EffectiveTo,null,null,B64(r.RowVersion)); }

    public async Task<V180MasterDataRow> SaveDeploymentSiteAsync(CurrentUserDto a,int? id,V180DeploymentSiteInput x,CancellationToken ct)
    { V180MasterDataValidationService.Period(x.EffectiveFrom,x.EffectiveTo);var c=await Center(a,x.CenterCode,ct);if(!Covers(c.EffectiveFrom,c.EffectiveTo,x.EffectiveFrom,x.EffectiveTo))throw new InvalidOperationException("SITE_OUTSIDE_CENTER_PERIOD");var l=await db.Locations.SingleOrDefaultAsync(z=>z.LocationCode==x.LocationCode&&z.OrganizationId==Org(a),ct)??throw new InvalidOperationException("UNKNOWN_LOCATION_CODE");if(l.ApprovalStatus!="Approved")throw new InvalidOperationException("LOCATION_NOT_APPROVED");if(!l.IsActive)throw new InvalidOperationException("LOCATION_NOT_ACTIVE");var r=id.HasValue?await db.DeploymentSites.SingleAsync(z=>z.DeploymentSiteId==id&&z.CenterId==c.CenterId,ct):new DeploymentSite{CenterId=c.CenterId,CreatedAt=DateTime.UtcNow};if(id.HasValue)V180MasterDataValidationService.RowVersion(x.RowVersion,r.RowVersion);r.SiteCode=x.SiteCode.Trim();r.SiteName=x.SiteName.Trim();r.EffectiveFrom=x.EffectiveFrom;r.EffectiveTo=x.EffectiveTo;r.IsActive=x.IsActive;if(!id.HasValue)db.DeploymentSites.Add(r);await db.SaveChangesAsync(ct);var link=await db.DeploymentSiteLocationAssignments.SingleOrDefaultAsync(z=>z.DeploymentSiteId==r.DeploymentSiteId,ct);if(link is null){link=new DeploymentSiteLocationAssignment{DeploymentSiteId=r.DeploymentSiteId,CreatedAt=DateTime.UtcNow};db.DeploymentSiteLocationAssignments.Add(link);}link.LocationId=l.LocationId;link.EffectiveFrom=x.EffectiveFrom;link.EffectiveTo=x.EffectiveTo;await SaveAudit(a,"DeploymentSite",r.SiteCode,id.HasValue?"Update":"Create",ct);await db.SaveChangesAsync(ct);return new(r.DeploymentSiteId,r.SiteCode,c.CenterCode,r.SiteName,r.EffectiveFrom,r.EffectiveTo,r.IsActive,null,B64(r.RowVersion)); }

    public async Task<V180MasterDataRow> SaveTeamSiteAsync(CurrentUserDto a,long? id,V180TeamSiteInput x,CancellationToken ct)
    { V180MasterDataValidationService.Period(x.EffectiveFrom,x.EffectiveTo);var t=await Team(a,x.TeamCode,ct);var s=await Site(a,x.SiteCode,ct);if(!await db.Set<TeamCenterAssignment>().AnyAsync(z=>z.TeamId==t.TeamId&&z.CenterId==s.CenterId&&Covers(z.EffectiveFrom,z.EffectiveTo,x.EffectiveFrom,x.EffectiveTo),ct))throw new InvalidOperationException("TEAM_SITE_WITHOUT_TEAM_CENTER_COVERAGE");var q=db.TeamDeploymentSiteAssignments.Where(z=>z.TeamId==t.TeamId);if(await q.AnyAsync(z=>(!id.HasValue||z.TeamDeploymentSiteAssignmentId!=id)&&V180MasterDataValidationService.Overlaps(x.EffectiveFrom,x.EffectiveTo,z.EffectiveFrom,z.EffectiveTo),ct))throw new InvalidOperationException("OVERLAPPING_TEAM_SITE");var r=id.HasValue?await q.SingleAsync(z=>z.TeamDeploymentSiteAssignmentId==id,ct):new TeamDeploymentSiteAssignment{TeamId=t.TeamId};if(id.HasValue)V180MasterDataValidationService.RowVersion(x.RowVersion,r.RowVersion);r.DeploymentSiteId=s.DeploymentSiteId;r.EffectiveFrom=x.EffectiveFrom;r.EffectiveTo=x.EffectiveTo;if(!id.HasValue)db.Add(r);await SaveAudit(a,"TeamDeploymentSiteAssignment",r.TeamDeploymentSiteAssignmentId.ToString(),id.HasValue?"Update":"Create",ct);await db.SaveChangesAsync(ct);return new(r.TeamDeploymentSiteAssignmentId,t.TeamCode,s.SiteCode,null,r.EffectiveFrom,r.EffectiveTo,null,null,B64(r.RowVersion)); }

    public async Task<V180MasterDataRow> SaveEmploymentSiteAsync(CurrentUserDto a,long? id,V180EmploymentSiteInput x,CancellationToken ct)
    { V180MasterDataValidationService.Period(x.EffectiveFrom,x.EffectiveTo);var e=await Employment(a,x.EmployeeNo,ct);var s=await Site(a,x.SiteCode,ct);if(!await db.EmploymentStatusPeriods.AnyAsync(z=>z.EmploymentId==e.EmploymentId&&z.EmploymentStatus=="Active"&&Covers(z.EffectiveFrom,z.EffectiveTo,x.EffectiveFrom,x.EffectiveTo),ct))throw new InvalidOperationException("EMPLOYMENT_SITE_WITHOUT_ACTIVE_EMPLOYMENT");var memberships=db.TeamMemberships.Where(z=>z.EmploymentId==e.EmploymentId&&Covers(z.EffectiveFrom,z.EffectiveTo,x.EffectiveFrom,x.EffectiveTo));if(!await memberships.AnyAsync(ct))throw new InvalidOperationException("EMPLOYMENT_SITE_WITHOUT_TEAM_MEMBERSHIP");var teams=memberships.Select(z=>z.TeamId);if(!await db.TeamDeploymentSiteAssignments.AnyAsync(z=>z.DeploymentSiteId==s.DeploymentSiteId&&teams.Contains(z.TeamId)&&Covers(z.EffectiveFrom,z.EffectiveTo,x.EffectiveFrom,x.EffectiveTo),ct))throw new InvalidOperationException("EMPLOYMENT_SITE_WITHOUT_TEAM_SITE_COVERAGE");var q=db.EmploymentDeploymentSiteAssignments.Where(z=>z.EmploymentId==e.EmploymentId);if(x.IsPrimary&&await q.AnyAsync(z=>(!id.HasValue||z.EmploymentDeploymentSiteAssignmentId!=id)&&z.IsPrimary&&V180MasterDataValidationService.Overlaps(x.EffectiveFrom,x.EffectiveTo,z.EffectiveFrom,z.EffectiveTo),ct))throw new InvalidOperationException("MULTIPLE_PRIMARY_EMPLOYMENT_SITE");var r=id.HasValue?await q.SingleAsync(z=>z.EmploymentDeploymentSiteAssignmentId==id,ct):new EmploymentDeploymentSiteAssignment{EmploymentId=e.EmploymentId,CreatedAt=DateTime.UtcNow};if(id.HasValue)V180MasterDataValidationService.RowVersion(x.RowVersion,r.RowVersion);r.DeploymentSiteId=s.DeploymentSiteId;r.IsPrimary=x.IsPrimary;r.EffectiveFrom=x.EffectiveFrom;r.EffectiveTo=x.EffectiveTo;if(!id.HasValue)db.EmploymentDeploymentSiteAssignments.Add(r);await SaveAudit(a,"EmploymentDeploymentSiteAssignment",r.EmploymentDeploymentSiteAssignmentId.ToString(),id.HasValue?"Update":"Create",ct);await db.SaveChangesAsync(ct);return new(r.EmploymentDeploymentSiteAssignmentId,e.EmployeeNo??"",s.SiteCode,null,r.EffectiveFrom,r.EffectiveTo,null,r.IsPrimary,B64(r.RowVersion)); }

    private async Task<Employment> Employment(CurrentUserDto a,string n,CancellationToken ct)=>await db.Employments.SingleOrDefaultAsync(x=>x.OrganizationId==Org(a)&&x.EmployeeNo==n.Trim(),ct)??throw new InvalidOperationException("UNKNOWN_EMPLOYEE_NO");
    private async Task<Team> Team(CurrentUserDto a,string n,CancellationToken ct)=>await db.Teams.SingleOrDefaultAsync(x=>x.OrganizationId==Org(a)&&x.TeamCode==n.Trim(),ct)??throw new InvalidOperationException("UNKNOWN_TEAM_CODE");
    private async Task<Center> Center(CurrentUserDto a,string n,CancellationToken ct)=>await db.Centers.SingleOrDefaultAsync(x=>x.OrganizationId==Org(a)&&x.CenterCode==n.Trim(),ct)??throw new InvalidOperationException("UNKNOWN_CENTER_CODE");
    private async Task<DeploymentSite> Site(CurrentUserDto a,string n,CancellationToken ct)=>await (from s in db.DeploymentSites join c in db.Centers on s.CenterId equals c.CenterId where c.OrganizationId==Org(a)&&s.SiteCode==n.Trim() select s).SingleOrDefaultAsync(ct)??throw new InvalidOperationException("UNKNOWN_SITE_CODE");
    private async Task SaveAudit(CurrentUserDto a,string type,string id,string action,CancellationToken ct)=>await db.AuditLogs.AddAsync(new AuditLog{UserId=a.UserId,EntityType=type,EntityId=id,Action=action,CreatedAt=DateTime.UtcNow},ct);
    private static int Org(CurrentUserDto a)=>a.OrganizationId??throw new InvalidOperationException("目前管理者缺少 OrganizationId。"); private static string? B64(byte[] b)=>b.Length==0?null:Convert.ToBase64String(b); private static bool Covers(DateOnly f,DateOnly? t,DateOnly a,DateOnly? b)=>f<=a&&(!t.HasValue||(!b.HasValue?false:t>=b));
}
