using FieldVisit.Application;
using FieldVisit.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace FieldVisit.DAIntegration.Integration.Tests;

internal static class Program
{
    static string Cs=""; static int passed,total;
    public static async Task<int> Main(){Cs=Environment.GetEnvironmentVariable("DA1B_CONNECTION_STRING")??throw new InvalidOperationException("DA1B_CONNECTION_STRING required");
        await Run("DAI-IT-A governance GET same-org",GetSameOrg);await Run("DAI-IT-B governance GET cross/global fail",GetScopeFail);await Run("DAI-IT-C summary same-org",SummarySameOrg);await Run("DAI-IT-D summary global omitted",SummaryGlobal);await Run("DAI-IT-E candidates same-org only",CandidatesSameOrg);await Run("DAI-IT-F candidates self excluded",CandidatesSelf);await Run("DAI-IT-G candidates global excluded",CandidatesGlobal);await Run("DAI-IT-H duplicate TaxId multiple",CandidatesDuplicateTax);await Run("DAI-IT-I impact current boundaries",ImpactBoundaries);await Run("DAI-IT-J impact historical excluded",ImpactHistorical);await Run("DAI-IT-K blocker projection",ImpactProjection);Console.WriteLine($"DAI_SQL_INTEGRATION={passed}/{total}=PASS");return 0;}
    static async Task Run(string n,Func<Task> f){total++;try{await f();passed++;Console.WriteLine($"{n}=PASS");}catch(Exception e){Console.Error.WriteLine($"{n}=FAIL: {e.GetType().Name}: {e.Message}");throw;}}
    static AppDbContext Db()=>new(new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(Cs).Options); static V180ManagedLocationGovernanceRepository Repo(AppDbContext d)=>new(d); static CurrentUserDto Admin()=>new(1,"E1","Admin",null,1,null,null,new[]{"admin"});
    static async Task Reset(){await using var d=Db();await d.Database.ExecuteSqlRawAsync("DELETE dbo.AuditLogs; DELETE dbo.DeploymentSiteLocationAssignments; DELETE dbo.DeploymentSites; DELETE dbo.EmploymentRoleAssignments; DELETE dbo.EmploymentStatusPeriods; DELETE dbo.UserIdentityProfiles; DELETE dbo.Employments; DELETE dbo.Persons; UPDATE dbo.Locations SET DuplicateOfLocationId=NULL,DuplicateReason=NULL; DELETE dbo.Locations; DELETE dbo.Users;");}
    static async Task SeedAuth(AppDbContext d){var today=BusinessTime.Today;await d.Database.ExecuteSqlRawAsync("INSERT dbo.Users(UserId,OrganizationId,EmployeeNo,DisplayName,IsActive) VALUES(1,1,'E1','Admin',1); INSERT dbo.Persons(PersonId,DisplayName,CreatedAt) VALUES(2001,'Admin',SYSUTCDATETIME()); INSERT dbo.Employments(EmploymentId,PersonId,OrganizationId,EmployeeNo,SourceType,CreatedAt) VALUES(1001,2001,1,'E1','Test',SYSUTCDATETIME());");await d.Database.ExecuteSqlInterpolatedAsync($"INSERT dbo.EmploymentStatusPeriods(EmploymentId,EmploymentStatus,EffectiveFrom,SourceType,CreatedAt) VALUES(1001,'Active',{today.AddDays(-10)},'Test',SYSUTCDATETIME())");await d.Database.ExecuteSqlInterpolatedAsync($"INSERT dbo.EmploymentRoleAssignments(EmploymentId,RoleId,EffectiveFrom,CreatedAt) VALUES(1001,1,{today.AddDays(-10)},SYSUTCDATETIME())");await d.Database.ExecuteSqlRawAsync("INSERT dbo.UserIdentityProfiles(UserId,EmploymentId,UserType,UserCode,IdentityProvider,CreatedAt) VALUES(1,1001,'Internal','U1','Test',SYSUTCDATETIME())");}
    static async Task Loc(AppDbContext d,int id,int? org=1,string name="Alpha",string? tax=null){await d.Database.ExecuteSqlInterpolatedAsync($@"INSERT dbo.Locations(LocationId,OrganizationId,TeamId,LocationCode,LocationName,LocationType,Address,IsTemporary,ApprovalStatus,GeocodingStatus,IsActive,CreatedAt,UpdatedAt,TaxId) VALUES({id},{org},{(org==1?(int?)10:org==2?20:null)},{"L"+id},{name},'Official',{"Addr "+id},0,'Approved','Success',1,SYSUTCDATETIME(),SYSUTCDATETIME(),{tax})");}
    static async Task Setup(){await Reset();await using var d=Db();await SeedAuth(d);}
    static async Task GetSameOrg(){await Setup();await using var d=Db();await Loc(d,1,tax:"123");await d.Database.ExecuteSqlRawAsync("UPDATE dbo.Locations SET MasterNote='M' WHERE LocationId=1");var x=await Repo(d).GetGovernanceAsync(Admin(),1,default);Eq("123",x.TaxId);Eq("M",x.MasterNote);Eq("L1",x.LocationCode);}
    static async Task GetScopeFail(){await Setup();await using var d=Db();await Loc(d,1,2);await Loc(d,2,null);await Throws<UnauthorizedAccessException>(()=>Repo(d).GetGovernanceAsync(Admin(),1,default));await Throws<UnauthorizedAccessException>(()=>Repo(d).GetGovernanceAsync(Admin(),2,default));}
    static async Task SummarySameOrg(){await Setup();await using var d=Db();await Loc(d,1,tax:"TAX");await Loc(d,2);await d.Database.ExecuteSqlRawAsync("UPDATE dbo.Locations SET DuplicateOfLocationId=2,DuplicateReason='r' WHERE LocationId=1");var x=await Repo(d).GetGovernanceSummariesAsync(Admin(),new[]{1},default);Eq(1,x.Count);Eq("TAX",x[0].TaxId);True(x[0].HasDuplicateReference);}
    static async Task SummaryGlobal(){await Setup();await using var d=Db();await Loc(d,1,null,tax:"SECRET");var x=await Repo(d).GetGovernanceSummariesAsync(Admin(),new[]{1},default);Eq(0,x.Count);}
    static async Task CandidatesSameOrg(){await Setup();await using var d=Db();await Loc(d,1);await Loc(d,2,1,"Beta");await Loc(d,3,2,"Other");var x=await Repo(d).SearchGovernanceCandidatesAsync(Admin(),1,null,1,20,default);Seq(new[]{2},x.Items.Select(v=>v.LocationId));}
    static async Task CandidatesSelf(){await Setup();await using var d=Db();await Loc(d,1);var x=await Repo(d).SearchGovernanceCandidatesAsync(Admin(),1,null,1,20,default);True(x.Items.All(v=>v.LocationId!=1));}
    static async Task CandidatesGlobal(){await Setup();await using var d=Db();await Loc(d,1);await Loc(d,2,null,"Global");var x=await Repo(d).SearchGovernanceCandidatesAsync(Admin(),1,null,1,20,default);True(x.Items.All(v=>v.LocationId!=2));}
    static async Task CandidatesDuplicateTax(){await Setup();await using var d=Db();await Loc(d,1);await Loc(d,2,1,"Beta","DUP");await Loc(d,3,1,"Gamma","DUP");var x=await Repo(d).SearchGovernanceCandidatesAsync(Admin(),1,"DUP",1,20,default);Seq(new[]{2,3},x.Items.Select(v=>v.LocationId).OrderBy(v=>v));}
    static async Task SeedSite(AppDbContext d,int site,int location,DateOnly? end,string code,string name){await d.Database.ExecuteSqlInterpolatedAsync($"INSERT dbo.DeploymentSites(DeploymentSiteId) VALUES({site})");await d.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.DeploymentSites SET SiteCode={code},SiteName={name} WHERE DeploymentSiteId={site}");await d.Database.ExecuteSqlInterpolatedAsync($"INSERT dbo.DeploymentSiteLocationAssignments(DeploymentSiteId,LocationId,EffectiveFrom,EffectiveTo) VALUES({site},{location},{BusinessTime.Today.AddDays(-5)},{end})");}
    static async Task ImpactBoundaries(){await Setup();await using var d=Db();await Loc(d,1);await SeedSite(d,101,1,null,"S1","NoEnd");await SeedSite(d,102,1,BusinessTime.Today,"S2","Today");await SeedSite(d,103,1,BusinessTime.Today.AddDays(1),"S3","Future");var x=await Repo(d).GetInactivationImpactAsync(Admin(),1,default);Eq(3,x.Blockers.Count);True(!x.CanDeactivate);}
    static async Task ImpactHistorical(){await Setup();await using var d=Db();await Loc(d,1);await SeedSite(d,101,1,BusinessTime.Today.AddDays(-1),"S1","Old");var x=await Repo(d).GetInactivationImpactAsync(Admin(),1,default);Eq(0,x.Blockers.Count);True(x.CanDeactivate);}
    static async Task ImpactProjection(){await Setup();await using var d=Db();await Loc(d,1);var end=BusinessTime.Today.AddDays(2);await SeedSite(d,123,1,end,"SITE123","Site Name");var b=(await Repo(d).GetInactivationImpactAsync(Admin(),1,default)).Blockers.Single();Eq(123,b.DeploymentSiteId);Eq("SITE123",b.DeploymentSiteCode);Eq("Site Name",b.DeploymentSiteName);Eq(BusinessTime.Today.AddDays(-5),b.EffectiveFrom);Eq(end,b.EffectiveTo);}
    static async Task<T> Throws<T>(Func<Task> f)where T:Exception{try{await f();}catch(T e){return e;}throw new Exception($"Expected {typeof(T).Name}");}static void True(bool v){if(!v)throw new Exception("Assertion failed");}static void Eq<T>(T e,T a){if(!EqualityComparer<T>.Default.Equals(e,a))throw new Exception($"Expected {e}, got {a}");}static void Seq<T>(IEnumerable<T>e,IEnumerable<T>a){if(!e.SequenceEqual(a))throw new Exception("Sequence mismatch");}
}
