import {useEffect,useMemo,useState} from "react";
import {api} from "../api";
import type {MileageRate,MileageReport,Project,VisitType} from "../types";
import {downloadCsv,money} from "../utils";

type Props={section:"dashboard"|"users"|"projects"|"rates"|"reports"};
const effectiveRate=(rates:MileageRate[],date:string)=>rates.filter(r=>r.isActive&&r.effectiveFrom<=date&&(!r.effectiveTo||r.effectiveTo>=date)).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0];

export default function AdminPage({section}:Props){
  const today=new Date().toISOString().slice(0,10);
  const [rates,setRates]=useState<MileageRate[]>([]),[report,setReport]=useState<MileageReport[]>([]),[projects,setProjects]=useState<Project[]>([]),[types,setTypes]=useState<VisitType[]>([]),[rate,setRate]=useState("2.50"),[date,setDate]=useState(today),[note,setNote]=useState(""),[msg,setMsg]=useState(""),[start,setStart]=useState("2026-01-01"),[end,setEnd]=useState(today),[status,setStatus]=useState(""),[team,setTeam]=useState("");
  const load=()=>Promise.all([api<MileageRate[]>("/mileage-rate-rules"),api<MileageReport[]>(`/reports/mileage?startDate=${start}&endDate=${end}`),api<Project[]>("/projects"),api<VisitType[]>("/visit-types")]).then(([r,m,p,v])=>{setRates(r);setReport(m);setProjects(p);setTypes(v)}).catch(e=>setMsg(e.message));
  useEffect(()=>{void load()},[section]);
  const add=async()=>{try{await api("/mileage-rate-rules",{method:"POST",body:JSON.stringify({ruleName:note.trim()||"機車里程補助",vehicleType:"Motorcycle",ratePerKm:Number(rate),effectiveFrom:date,effectiveTo:null})});setMsg("費率版本已新增；已核准歷史仍保留原費率與補助快照。");setNote("");await load()}catch(e){setMsg(e instanceof Error?e.message:"新增失敗")}};
  const current=effectiveRate(rates,today);
  const teams=useMemo(()=>[...new Set(report.map(x=>x.teamName).filter(Boolean) as string[])].sort(),[report]);
  const filtered=useMemo(()=>report.filter(x=>(!status||x.status===status)&&(!team||x.teamName===team)),[report,status,team]);
  const approved=report.filter(x=>x.status==="Approved");
  const reportDownload=(name:string,rows:MileageReport[]=report)=>downloadCsv(`${name}.csv`,rows.map(x=>({日期:x.visitDate,外訪員:x.visitorName,小組:x.teamName||"",路線:x.route,外訪員自算里程:x.claimedDistanceKm??"",系統里程:x.systemDistanceKm??"",小組長核定里程:x.approvedDistanceKm??"",每公里補助:x.ratePerKmSnapshot??"",補助金額:x.approvedAmount??"",狀態:x.statusName})));

  if(section==="dashboard")return <>
    <div className="grid cols-4"><div className="card stat"><div className="label">本期行程</div><div className="value">{report.length}</div><div className="hint">目前查詢資料</div></div><div className="card stat"><div className="label">已核准</div><div className="value">{approved.length}</div><div className="hint">含補助快照</div></div><div className="card stat"><div className="label">專案</div><div className="value">{projects.length}</div><div className="hint">目前可見專案</div></div><div className="card stat"><div className="label">目前每公里補助</div><div className="value">${money(current?.ratePerKm??0)}</div><div className="hint">依今天日期適用</div></div></div>
    <div className="grid cols-2" style={{marginTop:18}}><div className="card"><div className="section-title"><h2>補助費率管理</h2><span className="pill ok">生效日版本</span></div><div className="note">費率採生效日版本管理，歷史行程於核准時保存費率與補助金額快照，不會因後續調整而回溯改寫。</div></div><div className="card"><div className="section-title"><h2>目前 UAT 架構</h2><span className="pill">Schema 1.5.0</span></div><div className="route-list"><div className="route-item"><div className="route-index">1</div><div><div className="route-name">Azure SQL 真實資料</div><div className="route-address">行程、核准、補助費率與報表皆由 API 讀寫</div></div></div><div className="route-item"><div className="route-index">2</div><div><div className="route-name">無 API 使用量控制</div><div className="route-address">依需求，管理者不提供 API 配額／用量維護功能</div></div></div></div></div></div>
  </>;

  if(section==="rates")return <>
    <div className="grid cols-3"><div className="card stat"><div className="label">目前每公里補助</div><div className="value">${money(current?.ratePerKm??0)}</div><div className="hint">依今天日期套用</div></div><div className="card stat"><div className="label">費率版本數</div><div className="value">{rates.length}</div><div className="hint">保留歷史生效紀錄</div></div><div className="card stat"><div className="label">計算原則</div><div className="value" style={{fontSize:19}}>核定里程 × 費率</div><div className="hint">依行程日期抓取生效費率</div></div></div>
    <div className="card" style={{marginTop:18}}><div className="section-title"><div><h2>每公里補助費率</h2><div className="sub">新增新費率時必須設定生效日期。</div></div></div><div className="grid cols-3"><div className="field"><label>生效日期</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>每公里補助金額（元）</label><input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></div><div className="field"><label>備註／規則名稱</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：年度補助標準調整"/></div></div><button className="btn" onClick={()=>void add()}>＋新增費率版本</button>{msg&&<div className="note" style={{marginTop:12}}>{msg}</div>}<div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>生效日期</th><th>失效日期</th><th>每公里補助</th><th>狀態</th><th>規則</th></tr></thead><tbody>{[...rates].sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom)).map(r=><tr key={r.mileageRateRuleId}><td>{r.effectiveFrom}</td><td>{r.effectiveTo||"—"}</td><td><strong>${money(r.ratePerKm)}</strong></td><td><span className={`pill ${current?.mileageRateRuleId===r.mileageRateRuleId?"ok":""}`}>{current?.mileageRateRuleId===r.mileageRateRuleId?"目前適用":r.effectiveFrom<=today?"已生效":"未生效"}</span></td><td>{r.ruleName}</td></tr>)}</tbody></table></div><div className="note" style={{marginTop:14}}>已被歷史行程使用的費率不要刪除；新增新版費率，以生效日期區隔。</div></div>
  </>;

  if(section==="projects")return <><div className="grid cols-2"><div className="card"><div className="section-title"><h2>專案清單</h2><span className="pill">真實主檔</span></div><div className="table-wrap"><table><thead><tr><th>專案代碼</th><th>專案名稱</th><th>地點模式</th><th>狀態</th></tr></thead><tbody>{projects.map(p=><tr key={p.projectId}><td>{p.projectCode}</td><td>{p.projectName}</td><td><span className="pill">{p.locationMode}</span></td><td><span className={`pill ${p.isActive?"ok":"warn"}`}>{p.isActive?"啟用":"停用"}</span></td></tr>)}</tbody></table></div></div><div className="card"><div className="section-title"><h2>拜訪形式主檔</h2><span className="pill">真實主檔</span></div><div className="route-list">{types.map((v,i)=><div className="route-item" key={v.visitTypeId}><div className="route-index">{i+1}</div><div><div className="route-name">{v.visitTypeName}</div><div className="route-address">{v.visitTypeCode}</div></div></div>)}</div></div></div><div className="note" style={{marginTop:18}}>本輪先依 Prototype v2 恢復專案與拜訪形式的完整檢視介面；新增／編輯／匯入 API 將維持獨立模組，避免影響本次六項 UAT 重點功能。</div></>;

  if(section==="users")return <><div className="grid cols-2"><div className="card"><div className="section-title"><h2>人員與權限</h2><span className="pill">UAT</span></div><div className="note">正式環境以 Microsoft Entra ID 驗證身分；應用程式內仍保存角色、小組及資料範圍。此頁不提供 API 使用量控制。</div></div><div className="card"><div className="section-title"><h2>示範帳號</h2></div><div className="route-list">{[["visitor01","外訪員"],["visitor02","外訪員"],["leader01","小組長"],["admin01","管理者"],["gov01","督導"]].map(([a,r],i)=><div className="route-item" key={a}><div className="route-index">{i+1}</div><div><div className="route-name">{a}</div><div className="route-address">{r}｜UAT Seed</div></div></div>)}</div></div></div><div className="placeholder-box" style={{marginTop:18}}>人員批次匯入、新增帳號與角色異動屬於下一個 Master Data API 模組；目前不以假資料模擬寫入，避免 UAT 使用者誤以為已落入 Azure SQL。</div></>;

  const reportCards=[
    ["每日行程明細","外訪員、時間、路線、三種里程、補助費率與補助金額"],
    ["里程彙總報表","自算、系統、核定里程與補助金額"],
    ["地點使用分析","依路線關鍵字檢視地點使用情形，並保留補助資訊"],
    ["核准補助清單","已核准行程、費率快照與補助金額"]
  ];
  return <><div className="grid cols-3">{reportCards.map(([name,desc])=><div className="card report-card" key={name}><h2>{name}</h2><p>{desc}</p><button className="btn small secondary" onClick={()=>reportDownload(name,filtered)}>下載查詢結果</button></div>)}</div><div className="card" style={{marginTop:18}}><div className="section-title"><div><h2>報表查詢</h2><div className="sub">所有里程相關報表均顯示每公里補助與補助金額。</div></div><button className="btn" onClick={load}>查詢</button></div><div className="grid cols-4"><div className="field"><label>開始日期</label><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>結束日期</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><div className="field"><label>小組</label><select value={team} onChange={e=>setTeam(e.target.value)}><option value="">全部</option>{teams.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>狀態</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部</option><option value="Approved">已核准</option><option value="PendingApproval">待核准</option><option value="Submitted">已送出</option><option value="Returned">已退回</option></select></div></div>{msg&&<div className="note danger-note">{msg}</div>}<div className="table-wrap"><table><thead><tr><th>日期</th><th>外訪員</th><th>小組</th><th>路線</th><th>自算</th><th>系統</th><th>核定</th><th>每公里補助</th><th>補助金額</th><th>狀態</th></tr></thead><tbody>{filtered.map(x=><tr key={x.tripNo}><td>{x.visitDate}</td><td>{x.visitorName}</td><td>{x.teamName||"—"}</td><td>{x.route}</td><td>{x.claimedDistanceKm??"—"}</td><td>{x.systemDistanceKm??"—"}</td><td>{x.approvedDistanceKm??"—"}</td><td>{x.ratePerKmSnapshot==null?"—":`$${money(x.ratePerKmSnapshot)}`}</td><td className="subsidy-strong">{x.approvedAmount==null?"—":`$${money(x.approvedAmount)}`}</td><td>{x.statusName}</td></tr>)}</tbody></table></div></div></>;
}
