import {useEffect,useState} from "react";import {api} from "../api";import type {Location,Trip} from "../types";import {downloadCsv} from "../utils";
export default function LeaderPage(){const [trips,setTrips]=useState<Trip[]>([]),[pending,setPending]=useState<Location[]>([]),[mode,setMode]=useState("AllPending"),[start,setStart]=useState("2026-01-01"),[end,setEnd]=useState(new Date().toISOString().slice(0,10)),[locMode,setLocMode]=useState("all"),[locStart,setLocStart]=useState("2026-01-01"),[locEnd,setLocEnd]=useState(new Date().toISOString().slice(0,10)),[selected,setSelected]=useState<number[]>([]),[msg,setMsg]=useState("");
 const load=async()=>{try{const q=locMode==="range"?`?startDate=${locStart}&endDate=${locEnd}`:"";const [t,l]=await Promise.all([api<Trip[]>("/leader/review-queue"),api<Location[]>(`/locations/pending${q}`)]);setTrips(t);setPending(l)}catch(e){setMsg(e instanceof Error?e.message:"讀取失敗")}};useEffect(()=>{void load()},[]);
 const calc=async()=>{try{const r=await api<{success:number;failed:number;skipped:number}>("/mileage-jobs",{method:"POST",body:JSON.stringify({mode,startDate:mode==="DateRange"?start:null,endDate:mode==="DateRange"?end:null,selectedTripIds:null})});setMsg(`批次里程完成：成功 ${r.success}、失敗 ${r.failed}、略過 ${r.skipped}`);await load()}catch(e){setMsg(e instanceof Error?e.message:"計算失敗")}};
 const approve=async(t:Trip)=>{const x=prompt("核定里程",String(t.approvedDistanceKm??t.systemDistanceKm??0));if(x==null)return;try{await api(`/trips/${t.visitTripId}/approve`,{method:"POST",body:JSON.stringify({approvedDistanceKm:Number(x),rowVersion:t.rowVersion,comments:"UAT single approve"})});setMsg("核准完成，費率與補助快照已寫入 Azure SQL。");await load()}catch(e){setMsg(e instanceof Error?e.message:"核准失敗")}};
 const ret=async(t:Trip)=>{const reason=prompt("退回原因","里程或行程資料需確認");if(!reason)return;try{await api(`/trips/${t.visitTripId}/return`,{method:"POST",body:JSON.stringify({reason,rowVersion:t.rowVersion})});setMsg("已退回。");await load()}catch(e){setMsg(e instanceof Error?e.message:"退回失敗")}};
 const batchApprove=async()=>{const rows=trips.filter(t=>selected.includes(t.visitTripId)&&t.status==="PendingApproval");if(!rows.length)return setMsg("請先勾選待核准行程。");try{const r=await api<{success:number;failed:number;errors:string[]}>("/trips/batch-approve",{method:"POST",body:JSON.stringify({items:rows.map(t=>({visitTripId:t.visitTripId,approvedDistanceKm:t.approvedDistanceKm??t.systemDistanceKm??0,rowVersion:t.rowVersion}))})});setMsg(`批次核准：成功 ${r.success}、失敗 ${r.failed}${r.errors.length?`｜${r.errors.join("；")}`:""}`);setSelected([]);await load()}catch(e){setMsg(e instanceof Error?e.message:"批次核准失敗")}};
 const editLoc=async(l:Location)=>{const name=prompt("地點名稱",l.locationName);if(!name)return;const address=prompt("完整地址",l.address||"");const plus=prompt("Plus Code",l.plusCode||"");if(!address&&!plus)return setMsg("地址或 Plus Code 至少一項。");try{await api(`/locations/${l.locationId}`,{method:"PUT",body:JSON.stringify({locationName:name,city:l.city||null,district:l.district||null,address:address||null,plusCode:plus||null,rowVersion:l.rowVersion})});setMsg("地點已更新。");await load()}catch(e){setMsg(e instanceof Error?e.message:"更新失敗")}};
 const publish=async()=>{try{const r=await api<{success:number;failed:number;errors:string[]}>("/locations/batch-publish",{method:"POST",body:JSON.stringify({locationIds:pending.map(x=>x.locationId)})});setMsg(`地點發布：成功 ${r.success}、失敗 ${r.failed}${r.errors.length?`｜${r.errors.join("；")}`:""}`);await load()}catch(e){setMsg(e instanceof Error?e.message:"發布失敗")}};
 return <><div className="stats"><div className="card"><span>待處理</span><b>{trips.length}</b></div><div className="card"><span>未計算</span><b>{trips.filter(x=>x.systemDistanceKm==null).length}</b></div><div className="card"><span>待核准</span><b>{trips.filter(x=>x.status==="PendingApproval").length}</b></div><div className="card"><span>待發布地點</span><b>{pending.length}</b></div></div>
 <div className="card"><h2>批次里程計算</h2><div className="grid three"><label>模式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="AllPending">全部未計算</option><option value="DateRange">日期區間</option></select></label>{mode==="DateRange"&&<><label>開始<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>結束<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></>}</div><button className="btn" onClick={()=>void calc()}>開始批次計算</button><div className="alert">目前 UAT 使用 Mock Route Provider；流程與 Azure SQL 回寫是真實的，正式只替換 Provider。</div></div>
 <div className="card"><div className="head"><h2>行程審核</h2><div className="actions"><button className="btn secondary" onClick={()=>downloadCsv("小組長行程審核.csv",trips.map(t=>({日期:t.visitDate,外訪員:t.visitorName,路線:t.stops.map(s=>s.locationName).join(" → "),自算:t.claimedDistanceKm??"",系統:t.systemDistanceKm??"",核定:t.approvedDistanceKm??"",狀態:t.statusName})))}>下載</button><button className="btn ok" onClick={()=>void batchApprove()}>批次核准勾選</button></div></div>{msg&&<div className="alert">{msg}</div>}<div className="table"><table><thead><tr><th>選</th><th>日期</th><th>外訪員</th><th>路線</th><th>自算</th><th>系統</th><th>核定</th><th>狀態</th><th>操作</th></tr></thead><tbody>{trips.map(t=><tr key={t.visitTripId}><td><input type="checkbox" disabled={t.status!=="PendingApproval"} checked={selected.includes(t.visitTripId)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.visitTripId]:s.filter(x=>x!==t.visitTripId))}/></td><td>{t.visitDate}</td><td>{t.visitorName}</td><td>{t.stops.map(s=>s.locationName).join(" → ")}</td><td>{t.claimedDistanceKm??"—"}</td><td>{t.systemDistanceKm??"—"}</td><td>{t.approvedDistanceKm??"—"}</td><td>{t.statusName}</td><td>{t.status==="PendingApproval"&&<div className="actions"><button className="btn small ok" onClick={()=>void approve(t)}>核准</button><button className="btn small secondary" onClick={()=>void ret(t)}>退回</button></div>}</td></tr>)}</tbody></table></div></div>
 <div className="card"><div className="head"><h2>待確認／未上傳地點</h2><button className="btn" onClick={()=>void publish()}>批次發布查詢結果</button></div><div className="grid three"><label>模式<select value={locMode} onChange={e=>setLocMode(e.target.value)}><option value="all">全部未上傳</option><option value="range">日期區間</option></select></label>{locMode==="range"&&<><label>開始<input type="date" value={locStart} onChange={e=>setLocStart(e.target.value)}/></label><label>結束<input type="date" value={locEnd} onChange={e=>setLocEnd(e.target.value)}/></label></>}</div><button className="btn secondary" onClick={()=>void load()}>套用查詢</button><div className="table"><table><thead><tr><th>地點</th><th>地址/Plus Code</th><th>Geocoding</th><th>操作</th></tr></thead><tbody>{pending.map(l=><tr key={l.locationId}><td>{l.locationName}</td><td>{l.address||l.plusCode}</td><td>{l.geocodingStatus}</td><td><button className="btn small secondary" onClick={()=>void editLoc(l)}>修正</button></td></tr>)}</tbody></table></div></div></>}
