import {useEffect,useMemo,useState} from "react";
import {api} from "../api";
import type {Location,MileageRate,Trip} from "../types";
import {downloadCsv,money} from "../utils";

type Props={section:"dashboard"|"review"|"locations"};
type BatchResult={total:number;success:number;failed:number;skipped:number;items?:Array<{visitTripId:number;tripNo:string;status:string;systemDistanceKm?:number;errorCode?:string;errorMessage?:string}>};
type PublishResult={success:number;failed:number;errors:string[]};
const applicableRate=(rates:MileageRate[],date:string)=>rates.filter(r=>r.isActive&&r.effectiveFrom<=date&&(!r.effectiveTo||r.effectiveTo>=date)).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]?.ratePerKm;

export default function LeaderPage({section}:Props){
  const today=new Date().toISOString().slice(0,10);
  const [trips,setTrips]=useState<Trip[]>([]),[pending,setPending]=useState<Location[]>([]),[rates,setRates]=useState<MileageRate[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  const [mode,setMode]=useState("AllPending"),[start,setStart]=useState("2026-01-01"),[end,setEnd]=useState(today),[selected,setSelected]=useState<number[]>([]),[reviewKm,setReviewKm]=useState<Record<number,string>>({});
  const [locMode,setLocMode]=useState("all"),[locStart,setLocStart]=useState("2026-01-01"),[locEnd,setLocEnd]=useState(today),[locSelected,setLocSelected]=useState<number[]>([]),[editing,setEditing]=useState<Location|null>(null),[editAddress,setEditAddress]=useState(""),[editPlus,setEditPlus]=useState("");

  const load=async()=>{try{const q=locMode==="range"?`?startDate=${locStart}&endDate=${locEnd}`:"";const [t,l,r]=await Promise.all([api<Trip[]>("/leader/review-queue"),api<Location[]>(`/locations/pending${q}`),api<MileageRate[]>("/mileage-rate-rules")]);setTrips(t);setPending(l);setRates(r);setLocSelected(l.map(x=>x.locationId));const kmMap:Record<number,string>={};t.forEach(x=>{kmMap[x.visitTripId]=String(x.approvedDistanceKm??x.systemDistanceKm??x.claimedDistanceKm??0)});setReviewKm(kmMap)}catch(e){setMsg(e instanceof Error?e.message:"讀取失敗")}};
  useEffect(()=>{void load()},[section]);

  const calc=async(calcMode=mode,ids?:number[])=>{
    if(calcMode==="Selected"&&(!ids||!ids.length))return setMsg("請先勾選要計算里程的行程。");
    setBusy(true);
    try{
      const r=await api<BatchResult>("/mileage-jobs",{method:"POST",body:JSON.stringify({mode:calcMode,startDate:calcMode==="DateRange"?start:null,endDate:calcMode==="DateRange"?end:null,selectedTripIds:calcMode==="Selected"?ids:null})});
      const details=(r.items||[]).filter(x=>x.status!=="Success").map(x=>`${x.tripNo}：${x.errorMessage||x.errorCode||x.status}`);
      setMsg(`批次里程完成：成功 ${r.success}、失敗 ${r.failed}、略過 ${r.skipped}${details.length?`｜${details.join("；")}`:""}`);
      await load();
    }catch(e){setMsg(e instanceof Error?e.message:"計算失敗")}finally{setBusy(false)}
  };
  const approve=async(t:Trip)=>{const km=Number(reviewKm[t.visitTripId]??t.approvedDistanceKm??t.systemDistanceKm??0);if(km<0||!Number.isFinite(km))return setMsg("請輸入正確的核定里程。");setBusy(true);try{await api(`/trips/${t.visitTripId}/approve`,{method:"POST",body:JSON.stringify({approvedDistanceKm:km,rowVersion:t.rowVersion,comments:"UAT single approve"})});setMsg(`已核准 ${t.visitorName}，補助費率與金額已寫入 Azure SQL。`);await load()}catch(e){setMsg(e instanceof Error?e.message:"核准失敗")}finally{setBusy(false)}};
  const ret=async(t:Trip)=>{const reason=window.prompt("退回原因","時間重疊／里程或行程資料需確認");if(!reason)return;setBusy(true);try{await api(`/trips/${t.visitTripId}/return`,{method:"POST",body:JSON.stringify({reason,rowVersion:t.rowVersion})});setMsg("行程已退回。");await load()}catch(e){setMsg(e instanceof Error?e.message:"退回失敗")}finally{setBusy(false)}};
  const batchApprove=async()=>{const rows=trips.filter(t=>selected.includes(t.visitTripId)&&t.status==="PendingApproval");if(!rows.length)return setMsg("請先勾選待核准行程。");setBusy(true);try{const r=await api<{success:number;failed:number;errors:string[]}>("/trips/batch-approve",{method:"POST",body:JSON.stringify({items:rows.map(t=>({visitTripId:t.visitTripId,approvedDistanceKm:Number(reviewKm[t.visitTripId]??t.systemDistanceKm??0),rowVersion:t.rowVersion}))})});setMsg(`批次核准：成功 ${r.success}、失敗 ${r.failed}${r.errors.length?`｜${r.errors.join("；")}`:""}`);setSelected([]);await load()}catch(e){setMsg(e instanceof Error?e.message:"批次核准失敗")}finally{setBusy(false)}};
  const publish=async()=>{if(!locSelected.length)return setMsg("請先勾選要發布的地點。");setBusy(true);try{const r=await api<PublishResult>("/locations/batch-publish",{method:"POST",body:JSON.stringify({locationIds:locSelected})});setMsg(`地點批次處理：成功 ${r.success}、失敗 ${r.failed}${r.errors.length?`｜${r.errors.join("；")}`:""}`);await load()}catch(e){setMsg(e instanceof Error?e.message:"發布失敗")}finally{setBusy(false)}};
  const saveLocation=async()=>{if(!editing)return;if(!editAddress.trim()&&!editPlus.trim())return setMsg("完整地址與 Plus Code 至少需要一項。");setBusy(true);try{await api(`/locations/${editing.locationId}`,{method:"PUT",body:JSON.stringify({locationName:editing.locationName,city:editing.city||null,district:editing.district||null,address:editAddress.trim()||null,plusCode:editPlus.trim()||null,rowVersion:editing.rowVersion})});setEditing(null);setMsg("地點已更新，可重新執行批次解析與發布。");await load()}catch(e){setMsg(e instanceof Error?e.message:"更新失敗")}finally{setBusy(false)}};

  const pendingMileage=trips.filter(x=>x.systemDistanceKm==null).length;
  const pendingApproval=trips.filter(x=>x.status==="PendingApproval").length;
  const approved=trips.filter(x=>x.status==="Approved").length;
  const previewAmount=(t:Trip)=>{const r=applicableRate(rates,t.visitDate);const km=Number(reviewKm[t.visitTripId]??t.approvedDistanceKm??t.systemDistanceKm??0);return r==null?null:Math.round(km*r*100)/100};
  const reviewDownload=()=>downloadCsv("小組長行程審核.csv",trips.map(t=>({日期:t.visitDate,外訪員:t.visitorName,路線:t.stops.map(s=>s.locationName).join(" → "),自算:t.claimedDistanceKm??"",系統:t.systemDistanceKm??"",小組長核定:reviewKm[t.visitTripId]??t.approvedDistanceKm??"",每公里補助:applicableRate(rates,t.visitDate)??"",補助金額:previewAmount(t)??t.approvedAmount??"",狀態:t.statusName})));
  const reviewIds=trips.map(t=>t.visitTripId);
  const allReviewSelected=reviewIds.length>0&&reviewIds.every(id=>selected.includes(id));
  const toggleAllReview=()=>setSelected(allReviewSelected?[]:reviewIds);
  const selectPendingMileage=()=>setSelected(trips.filter(t=>t.systemDistanceKm==null).map(t=>t.visitTripId));

  if(section==="dashboard")return <>
    <div className="grid cols-4"><div className="card stat"><div className="label">待處理行程</div><div className="value">{trips.length}</div><div className="hint">目前小組範圍</div></div><div className="card stat"><div className="label">尚未計算里程</div><div className="value">{pendingMileage}</div><div className="hint">可跨日一次補算</div></div><div className="card stat"><div className="label">待核准</div><div className="value">{pendingApproval}</div><div className="hint">系統里程已完成</div></div><div className="card stat"><div className="label">已核准</div><div className="value">{approved}</div><div className="hint">本佇列目前資料</div></div></div>
    <div className="grid cols-2" style={{marginTop:18}}><div className="card"><div className="section-title"><h2>小組處理狀態</h2><span className="pill">Azure SQL 即時資料</span></div><div className="route-list"><div className="route-item"><div className="route-index">{pendingMileage}</div><div><div className="route-name">尚未計算里程</div><div className="route-address">已送出但尚未產生系統里程</div></div></div><div className="route-item"><div className="route-index">{pendingApproval}</div><div><div className="route-name">待小組長核准</div><div className="route-address">可調整核定里程後核准</div></div></div><div className="route-item"><div className="route-index">{pending.length}</div><div><div className="route-name">待確認／未上傳地點</div><div className="route-address">可依日期區間批次解析與發布</div></div></div></div></div>
      <div className="card"><div className="section-title"><h2>批次里程計算</h2><span className="pill">Route Provider</span></div><p className="muted">可一次補算所有歷史未計算行程，或只處理指定日期區間內尚未計算的資料。</p><div className="field"><label>計算模式</label><select value={mode} onChange={e=>setMode(e.target.value)}><option value="AllPending">全部未計算行程</option><option value="DateRange">指定日期區間</option></select></div>{mode==="DateRange"&&<div className="grid cols-2"><div className="field"><label>開始日期</label><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>結束日期</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div>}<div className="note">只處理尚無系統里程的行程；地點資料不完整者會回報失敗，不會阻斷其他行程。</div><button className="btn full" style={{marginTop:14}} disabled={busy} onClick={()=>void calc()}>{busy?"處理中…":"開始批次計算"}</button>{msg&&<div className="note" style={{marginTop:12}}>{msg}</div>}</div></div>
  </>;

  if(section==="review")return <div className="card"><div className="section-title"><div><h2>待審核行程</h2><div className="sub">核定里程預設等於系統里程；補助依行程日期套用當日有效費率。</div></div><div className="actions"><button className="btn outline" disabled={busy||!trips.length} onClick={selectPendingMileage}>勾選全部未計算</button><button className="btn ok" disabled={busy} onClick={()=>void batchApprove()}>批次核准勾選項目</button><button className="btn secondary" disabled={busy} onClick={()=>void calc("Selected",selected)}>計算／補算勾選項目</button><button className="btn outline" onClick={reviewDownload}>下載</button></div></div>{msg&&<div className="note">{msg}</div>}<div className="table-wrap"><table><thead><tr><th><label style={{display:"inline-flex",alignItems:"center",gap:6}}><input type="checkbox" checked={allReviewSelected} onChange={toggleAllReview}/>全選</label></th><th>日期</th><th>外訪員</th><th>拜訪順序</th><th>自算</th><th>系統</th><th>小組長核定</th><th>每公里補助</th><th>補助金額</th><th>狀態</th><th>操作</th></tr></thead><tbody>{trips.map(t=>{const rate=applicableRate(rates,t.visitDate);const amount=previewAmount(t);return <tr key={t.visitTripId}><td><input type="checkbox" checked={selected.includes(t.visitTripId)} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,t.visitTripId])]:s.filter(x=>x!==t.visitTripId))}/></td><td>{t.visitDate}</td><td>{t.visitorName}</td><td>{t.stops.map(s=>s.locationName).join(" → ")}</td><td>{t.claimedDistanceKm??"—"}</td><td>{t.systemDistanceKm??"—"}</td><td><input className="leader-km" type="number" step="0.1" min="0" value={reviewKm[t.visitTripId]??""} onChange={e=>setReviewKm(v=>({...v,[t.visitTripId]:e.target.value}))}/> km</td><td>{rate==null?"—":`$${money(rate)}`}</td><td className="subsidy-strong">{amount==null?"—":`$${money(amount)}`}</td><td><span className={`pill ${t.status==="Approved"?"ok":t.status==="Returned"?"danger":"warn"}`}>{t.statusName}</span></td><td>{t.status==="PendingApproval"?<div className="actions"><button className="btn small ok" disabled={busy} onClick={()=>void approve(t)}>核准</button><button className="btn small secondary" disabled={busy} onClick={()=>void ret(t)}>退回</button></div>:t.systemDistanceKm==null?<button className="btn small outline" disabled={busy} onClick={()=>void calc("Selected",[t.visitTripId])}>計算里程</button>:"—"}</td></tr>})}</tbody></table></div>{!trips.length&&<div className="empty">目前沒有待處理行程。</div>}</div>;

  return <>
    <div className="card"><div className="section-title"><div><h2>新增地點批次上傳／發布</h2><div className="sub">可選擇全部尚未上傳的地點，或指定日期區間。</div></div><span className="pill warn">{pending.length} 筆未上傳</span></div>
      <div className="grid cols-4"><div className="field"><label>處理模式</label><select value={locMode} onChange={e=>setLocMode(e.target.value)}><option value="all">全部未上傳地點</option><option value="range">指定日期區間</option></select></div>{locMode==="range"&&<><div className="field"><label>開始日期</label><input type="date" value={locStart} onChange={e=>setLocStart(e.target.value)}/></div><div className="field"><label>結束日期</label><input type="date" value={locEnd} onChange={e=>setLocEnd(e.target.value)}/></div></>}<div className="field"><label>&nbsp;</label><button className="btn" onClick={()=>void load()}>套用條件</button></div></div>
      <div className="actions" style={{marginBottom:14}}><button className="btn secondary" onClick={()=>setLocSelected(pending.map(x=>x.locationId))}>全選查詢結果</button><button className="btn outline" onClick={()=>setLocSelected([])}>取消全選</button><button className="btn ok" disabled={busy} onClick={()=>void publish()}>批次解析並上傳</button></div>{msg&&<div className="note">{msg}</div>}
      <div className="table-wrap"><table><thead><tr><th>選取</th><th>新增日期</th><th>地點</th><th>地址／Plus Code</th><th>解析狀態</th><th>操作</th></tr></thead><tbody>{pending.map(l=><tr key={l.locationId}><td><input type="checkbox" checked={locSelected.includes(l.locationId)} onChange={e=>setLocSelected(s=>e.target.checked?[...new Set([...s,l.locationId])]:s.filter(x=>x!==l.locationId))}/></td><td>{l.createdAt.slice(0,10)}</td><td>{l.locationName}</td><td>{l.address||l.plusCode||"—"}</td><td><span className={`pill ${l.geocodingStatus==="Completed"?"ok":l.geocodingStatus==="Failed"?"danger":"warn"}`}>{l.geocodingStatus}</span></td><td><button className="btn small outline" onClick={()=>{setEditing(l);setEditAddress(l.address||"");setEditPlus(l.plusCode||"")}}>維護／Plus Code</button></td></tr>)}</tbody></table></div>{!pending.length&&<div className="empty">此條件下沒有尚未上傳的地點。</div>}
    </div>
    <div className="grid cols-2" style={{marginTop:18}}><div className="card"><div className="section-title"><h2>處理說明</h2></div><div className="note">批次處理時，後端會呼叫目前設定的 Geocoding Provider；完整地址或 Plus Code 解析成功後，才會轉為正式地點。</div></div><div className="card"><div className="section-title"><h2>正式化提醒</h2></div><p className="muted">UAT 目前使用可替換 Provider；正式環境改接公司核准的 Google Geocoding / Routes 服務，前端流程不需重做。</p></div></div>
    {editing&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="modal-panel"><h3>維護地點位置</h3><div className="field"><label>地點名稱</label><input value={editing.locationName} disabled/></div><div className="field"><label>完整地址</label><input value={editAddress} onChange={e=>setEditAddress(e.target.value)} placeholder="輸入完整門牌地址"/></div><div className="field"><label>Plus Code</label><input value={editPlus} onChange={e=>setEditPlus(e.target.value)} placeholder="例如：2G7H+45 板橋區 新北市"/></div><div className="note">儲存後會標記為待解析；再由「批次解析並上傳」執行 Geocoding 與正式發布。</div><div className="actions" style={{marginTop:16}}><button className="btn ok" disabled={busy} onClick={()=>void saveLocation()}>儲存位置</button><button className="btn outline" onClick={()=>setEditing(null)}>取消</button></div></div></div>}
  </>;
}
