import{useEffect,useState,type ReactNode}from"react";
import{api,apiDownload}from"../api";
import{todayTaipei}from"../v160";

type ReadinessIssue={code:string;message:string;count:number};
type Readiness={asOfDate:string;ready:boolean;employmentCount:number;missingEmploymentStatusCount:number;teamCount:number;missingTeamCenterCount:number;activeDeploymentSiteCount:number;missingTeamSiteCount:number;missingEmploymentPrimarySiteCount:number;mileageRateReady:boolean;issues:ReadinessIssue[]};
type Employment={employmentId:number;employeeNo:string;displayName:string;employmentStatus?:string;statusEffectiveFrom?:string;statusEffectiveTo?:string;primaryTeamCode?:string;primaryTeamName?:string;primarySiteCode?:string;primarySiteName?:string};
type Team={teamId:number;teamCode:string;teamName:string;isActive:boolean;effectiveFrom?:string;effectiveTo?:string};
type Location={locationId:number;locationCode:string;locationName:string;address?:string;isActive:boolean;approvalStatus:string};
type Center={centerId:number;centerCode:string;centerName:string;effectiveFrom:string;effectiveTo?:string;isActive:boolean;notes?:string};
type TeamCenter={teamCenterAssignmentId:number;teamCode:string;teamName:string;centerCode:string;centerName:string;effectiveFrom:string;effectiveTo?:string;changeReason?:string};
type Site={deploymentSiteId:number;centerCode:string;siteCode:string;siteName:string;locationCode?:string;locationName?:string;effectiveFrom:string;effectiveTo?:string;isActive:boolean;notes?:string};
type TeamSite={teamDeploymentSiteAssignmentId:number;teamCode:string;siteCode:string;siteName:string;effectiveFrom:string;effectiveTo?:string};
type EmploymentSite={employmentDeploymentSiteAssignmentId:number;employeeNo:string;displayName:string;siteCode:string;siteName:string;isPrimary:boolean;effectiveFrom:string;effectiveTo?:string};
type Workspace={readiness:Readiness;employments:Employment[];teams:Team[];locations:Location[];centers:Center[];teamCenters:TeamCenter[];deploymentSites:Site[];teamSites:TeamSite[];employmentSites:EmploymentSite[]};
type SaveResult={entityType:string;action:string;displayKey:string};
type PreviewItem={rowNumber:number;sheet:string;entityType:string;action:string;displayKey:string;status:string;message?:string;isRetroactive:boolean};
type Preview={importBatchId:string;totalCount:number;validCount:number;errorCount:number;requiresRetroactiveConfirmation:boolean;items:PreviewItem[]};
type ConfirmResult={importBatchId:string;created:number;updated:number;unchanged:number;failed:number;errors:string[]};
type Tab='employment'|'centers'|'sites'|'team-sites'|'employment-sites';

const emptyDate=()=>todayTaipei();
const endText=(v?:string)=>v||'無期限';

export default function MasterDataSetupPage(){
 const[data,setData]=useState<Workspace|null>(null),[tab,setTab]=useState<Tab>('employment'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>setData(await api<Workspace>('/admin/master-data'));
 useEffect(()=>{void load().catch(e=>setMsg(e instanceof Error?e.message:'載入失敗'))},[]);
 const saved=async<T,>(path:string,body:T)=>{setBusy(true);setMsg('');try{const r=await api<SaveResult>(path,{method:'POST',body:JSON.stringify(body)});setMsg(`${r.displayKey}：${r.action==='Create'?'已新增':r.action==='Update'?'已更新':'無異動'}。`);await load()}catch(e){setMsg(e instanceof Error?e.message:'儲存失敗')}finally{setBusy(false)}};
 if(!data)return <div className="card">{msg||'載入主檔設定中…'}</div>;
 return <>
  <ReadinessPanel value={data.readiness}/>
  <div className="card" style={{marginTop:18}}><div className="section-title"><div><h2>UAT 主檔設定</h2><div className="sub">Business Admin 以 Business Key 維護；不需要輸入任何 DB ID。歷史資料不提供 Hard Delete。</div></div></div>
   <div className="actions" style={{flexWrap:'wrap'}}>
    <TabButton active={tab==='employment'} onClick={()=>setTab('employment')}>人員在職</TabButton>
    <TabButton active={tab==='centers'} onClick={()=>setTab('centers')}>Center / Team-Center</TabButton>
    <TabButton active={tab==='sites'} onClick={()=>setTab('sites')}>Deployment Site</TabButton>
    <TabButton active={tab==='team-sites'} onClick={()=>setTab('team-sites')}>Team-Site</TabButton>
    <TabButton active={tab==='employment-sites'} onClick={()=>setTab('employment-sites')}>Employment-Site</TabButton>
   </div>
  </div>
  {msg&&<div className="note" style={{marginTop:14}}>{msg}</div>}
  {tab==='employment'&&<EmploymentStatusPanel data={data} busy={busy} save={saved}/>}
  {tab==='centers'&&<CenterPanel data={data} busy={busy} save={saved}/>}
  {tab==='sites'&&<SitePanel data={data} busy={busy} save={saved}/>}
  {tab==='team-sites'&&<TeamSitePanel data={data} busy={busy} save={saved}/>}
  {tab==='employment-sites'&&<EmploymentSitePanel data={data} busy={busy} save={saved}/>}
  <BulkPanel busyOuter={busy} onConfirmed={load}/>
 </>;
}

function ReadinessPanel({value}:{value:Readiness}){
 const cards:[string,string|number,string][]=[
  ['人員',`${value.employmentCount-value.missingEmploymentStatusCount}/${value.employmentCount}`,'有效 Active'],
  ['Team-Center',`${value.teamCount-value.missingTeamCenterCount}/${value.teamCount}`,'小組已歸屬'],
  ['Deployment Site',value.activeDeploymentSiteCount,'目前啟用'],
  ['Team-Site',value.missingTeamSiteCount===0?'完成':`缺 ${value.missingTeamSiteCount}`,'目前有人員的小組'],
  ['Primary Site',value.missingEmploymentPrimarySiteCount===0?'完成':`缺 ${value.missingEmploymentPrimarySiteCount}`,'有效在職人員'],
  ['費率',value.mileageRateReady?'完成':'缺少','Motorcycle']
 ];
 return <><div className={`note ${value.ready?'ok-note':'warn-note'}`}><strong>{value.ready?'UAT READY':'UAT 主檔尚未準備完成'}</strong><div className="sub">檢核日：{value.asOfDate}。Readiness 是準備提示；實際 Trip API 仍維持 fail-closed 驗證。</div></div><div className="grid cols-3" style={{marginTop:14}}>{cards.map(([label,count,hint])=><div className="card stat" key={label}><div className="label">{label}</div><div className="value">{count}</div><div className="hint">{hint}</div></div>)}</div>{value.issues.length>0&&<div className="card" style={{marginTop:14}}><h3>待處理</h3>{value.issues.map(x=><div className="note warn-note" key={x.code}>{x.message}（{x.count}）</div>)}</div>}</>;
}
function TabButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button className={`btn small ${active?'ok':'outline'}`} onClick={onClick}>{children}</button>}

function EmploymentStatusPanel({data,busy,save}:{data:Workspace;busy:boolean;save:<T>(p:string,b:T)=>Promise<void>}){
 const[employeeNo,setEmployee]=useState(data.employments[0]?.employeeNo||''),[status,setStatus]=useState('Active'),[from,setFrom]=useState(emptyDate()),[to,setTo]=useState('');
 const open=(x:Employment)=>{setEmployee(x.employeeNo);setStatus(x.employmentStatus||'Active');setFrom(x.statusEffectiveFrom||emptyDate());setTo(x.statusEffectiveTo||'')};
 return <div className="card" style={{marginTop:18}}><h2>人員在職狀態</h2><div className="grid cols-3"><label>員工<select value={employeeNo} onChange={e=>setEmployee(e.target.value)}>{data.employments.map(x=><option value={x.employeeNo} key={x.employeeNo}>{x.employeeNo}｜{x.displayName}</option>)}</select></label><label>狀態<select value={status} onChange={e=>setStatus(e.target.value)}>{['Active','Leave','Terminated','PreHire'].map(x=><option key={x}>{x}</option>)}</select></label><label>生效日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>失效日<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="btn ok" disabled={busy||!employeeNo||!from} onClick={()=>void save('/admin/master-data/employment-status',{employeeNo,employmentStatus:status,effectiveFrom:from,effectiveTo:to||null})}>儲存在職期間</button><Table headers={['員編 / 姓名','目前狀態','有效期間','Primary Team','Primary Site','操作']} rows={data.employments.map(x=>[`${x.employeeNo}｜${x.displayName}`,x.employmentStatus||'缺少',x.statusEffectiveFrom?`${x.statusEffectiveFrom}～${endText(x.statusEffectiveTo)}`:'—',x.primaryTeamName||'—',x.primarySiteName||'—',<button className="btn small secondary" onClick={()=>open(x)}>帶入</button>])}/></div>
}

function CenterPanel({data,busy,save}:{data:Workspace;busy:boolean;save:<T>(p:string,b:T)=>Promise<void>}){
 const[code,setCode]=useState(''),[name,setName]=useState(''),[from,setFrom]=useState(emptyDate()),[to,setTo]=useState(''),[active,setActive]=useState(true),[notes,setNotes]=useState('');
 const[team,setTeam]=useState(data.teams[0]?.teamCode||''),[center,setCenter]=useState(data.centers[0]?.centerCode||''),[tcFrom,setTcFrom]=useState(emptyDate()),[tcTo,setTcTo]=useState(''),[reason,setReason]=useState('');
 const openCenter=(x:Center)=>{setCode(x.centerCode);setName(x.centerName);setFrom(x.effectiveFrom);setTo(x.effectiveTo||'');setActive(x.isActive);setNotes(x.notes||'')};
 const openTc=(x:TeamCenter)=>{setTeam(x.teamCode);setCenter(x.centerCode);setTcFrom(x.effectiveFrom);setTcTo(x.effectiveTo||'');setReason(x.changeReason||'')};
 return <div className="grid cols-2" style={{marginTop:18}}><div className="card"><h2>Center</h2><div className="grid cols-2"><label>Center Code<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>Center Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>生效日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>失效日<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>啟用</label><label>備註<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><button className="btn ok" disabled={busy||!code||!name||!from} onClick={()=>void save('/admin/master-data/centers',{centerCode:code,centerName:name,effectiveFrom:from,effectiveTo:to||null,isActive:active,notes:notes||null})}>儲存 Center</button><Table headers={['Code','名稱','期間','狀態','操作']} rows={data.centers.map(x=>[x.centerCode,x.centerName,`${x.effectiveFrom}～${endText(x.effectiveTo)}`,x.isActive?'啟用':'停用',<button className="btn small secondary" onClick={()=>openCenter(x)}>帶入</button>])}/></div><div className="card"><h2>Team → Center</h2><div className="grid cols-2"><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}>{data.teams.map(x=><option value={x.teamCode} key={x.teamCode}>{x.teamCode}｜{x.teamName}</option>)}</select></label><label>Center<select value={center} onChange={e=>setCenter(e.target.value)}>{data.centers.map(x=><option value={x.centerCode} key={x.centerCode}>{x.centerCode}｜{x.centerName}</option>)}</select></label><label>生效日<input type="date" value={tcFrom} onChange={e=>setTcFrom(e.target.value)}/></label><label>失效日<input type="date" value={tcTo} onChange={e=>setTcTo(e.target.value)}/></label><label className="span-2">原因<input value={reason} onChange={e=>setReason(e.target.value)}/></label></div><button className="btn ok" disabled={busy||!team||!center||!tcFrom} onClick={()=>void save('/admin/master-data/team-centers',{teamCode:team,centerCode:center,effectiveFrom:tcFrom,effectiveTo:tcTo||null,changeReason:reason||null})}>儲存 Team-Center</button><Table headers={['Team','Center','期間','操作']} rows={data.teamCenters.map(x=>[`${x.teamCode}｜${x.teamName}`,`${x.centerCode}｜${x.centerName}`,`${x.effectiveFrom}～${endText(x.effectiveTo)}`,<button className="btn small secondary" onClick={()=>openTc(x)}>帶入</button>])}/></div></div>
}

function SitePanel({data,busy,save}:{data:Workspace;busy:boolean;save:<T>(p:string,b:T)=>Promise<void>}){
 const approved=data.locations.filter(x=>x.isActive&&x.approvalStatus.toLowerCase()==='approved');
 const[center,setCenter]=useState(data.centers[0]?.centerCode||''),[code,setCode]=useState(''),[name,setName]=useState(''),[location,setLocation]=useState(approved[0]?.locationCode||''),[from,setFrom]=useState(emptyDate()),[to,setTo]=useState(''),[active,setActive]=useState(true),[notes,setNotes]=useState(''),[reason,setReason]=useState('');
 const open=(x:Site)=>{setCenter(x.centerCode);setCode(x.siteCode);setName(x.siteName);setLocation(x.locationCode||'');setFrom(x.effectiveFrom);setTo(x.effectiveTo||'');setActive(x.isActive);setNotes(x.notes||'')};
 return <div className="card" style={{marginTop:18}}><h2>Deployment Site</h2><div className="note">Location 必須先在「地點主檔」完成 Approved / 啟用，再於此建立 Deployment Site。</div><div className="grid cols-3"><label>Center<select value={center} onChange={e=>setCenter(e.target.value)}>{data.centers.map(x=><option value={x.centerCode} key={x.centerCode}>{x.centerCode}｜{x.centerName}</option>)}</select></label><label>Site Code<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>Site Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Location<select value={location} onChange={e=>setLocation(e.target.value)}>{approved.map(x=><option value={x.locationCode} key={x.locationCode}>{x.locationCode}｜{x.locationName}</option>)}</select></label><label>生效日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>失效日<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>啟用</label><label>備註<input value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>異動原因<input value={reason} onChange={e=>setReason(e.target.value)}/></label></div><button className="btn ok" disabled={busy||!center||!code||!name||!location||!from} onClick={()=>void save('/admin/master-data/deployment-sites',{centerCode:center,siteCode:code,siteName:name,locationCode:location,effectiveFrom:from,effectiveTo:to||null,isActive:active,notes:notes||null,changeReason:reason||null})}>儲存 Deployment Site</button><Table headers={['Site','Center','Location','期間','狀態','操作']} rows={data.deploymentSites.map(x=>[`${x.siteCode}｜${x.siteName}`,x.centerCode,x.locationCode?`${x.locationCode}｜${x.locationName||''}`:'缺少',`${x.effectiveFrom}～${endText(x.effectiveTo)}`,x.isActive?'啟用':'停用',<button className="btn small secondary" onClick={()=>open(x)}>帶入</button>])}/></div>
}

function TeamSitePanel({data,busy,save}:{data:Workspace;busy:boolean;save:<T>(p:string,b:T)=>Promise<void>}){
 const[team,setTeam]=useState(data.teams[0]?.teamCode||''),[site,setSite]=useState(data.deploymentSites[0]?.siteCode||''),[from,setFrom]=useState(emptyDate()),[to,setTo]=useState('');const open=(x:TeamSite)=>{setTeam(x.teamCode);setSite(x.siteCode);setFrom(x.effectiveFrom);setTo(x.effectiveTo||'')};
 return <div className="card" style={{marginTop:18}}><h2>Team → Site</h2><div className="grid cols-2"><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}>{data.teams.map(x=><option value={x.teamCode} key={x.teamCode}>{x.teamCode}｜{x.teamName}</option>)}</select></label><label>Site<select value={site} onChange={e=>setSite(e.target.value)}>{data.deploymentSites.map(x=><option value={x.siteCode} key={x.siteCode}>{x.siteCode}｜{x.siteName}</option>)}</select></label><label>生效日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>失效日<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="btn ok" disabled={busy||!team||!site||!from} onClick={()=>void save('/admin/master-data/team-sites',{teamCode:team,siteCode:site,effectiveFrom:from,effectiveTo:to||null})}>儲存 Team-Site</button><Table headers={['Team','Site','期間','操作']} rows={data.teamSites.map(x=>[x.teamCode,`${x.siteCode}｜${x.siteName}`,`${x.effectiveFrom}～${endText(x.effectiveTo)}`,<button className="btn small secondary" onClick={()=>open(x)}>帶入</button>])}/></div>
}

function EmploymentSitePanel({data,busy,save}:{data:Workspace;busy:boolean;save:<T>(p:string,b:T)=>Promise<void>}){
 const[employee,setEmployee]=useState(data.employments[0]?.employeeNo||''),[site,setSite]=useState(data.deploymentSites[0]?.siteCode||''),[primary,setPrimary]=useState(true),[from,setFrom]=useState(emptyDate()),[to,setTo]=useState('');const open=(x:EmploymentSite)=>{setEmployee(x.employeeNo);setSite(x.siteCode);setPrimary(x.isPrimary);setFrom(x.effectiveFrom);setTo(x.effectiveTo||'')};
 return <div className="card" style={{marginTop:18}}><h2>Employment → Site</h2><div className="grid cols-2"><label>員工<select value={employee} onChange={e=>setEmployee(e.target.value)}>{data.employments.map(x=><option value={x.employeeNo} key={x.employeeNo}>{x.employeeNo}｜{x.displayName}</option>)}</select></label><label>Site<select value={site} onChange={e=>setSite(e.target.value)}>{data.deploymentSites.map(x=><option value={x.siteCode} key={x.siteCode}>{x.siteCode}｜{x.siteName}</option>)}</select></label><label>生效日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>失效日<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={primary} onChange={e=>setPrimary(e.target.checked)}/>Primary Site</label></div><button className="btn ok" disabled={busy||!employee||!site||!from} onClick={()=>void save('/admin/master-data/employment-sites',{employeeNo:employee,siteCode:site,isPrimary:primary,effectiveFrom:from,effectiveTo:to||null})}>儲存 Employment-Site</button><Table headers={['員工','Site','Primary','期間','操作']} rows={data.employmentSites.map(x=>[`${x.employeeNo}｜${x.displayName}`,`${x.siteCode}｜${x.siteName}`,x.isPrimary?'是':'否',`${x.effectiveFrom}～${endText(x.effectiveTo)}`,<button className="btn small secondary" onClick={()=>open(x)}>帶入</button>])}/></div>
}

function BulkPanel({busyOuter,onConfirmed}:{busyOuter:boolean;onConfirmed:()=>Promise<void>}){
 const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[result,setResult]=useState<ConfirmResult|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const disabled=busy||busyOuter;
 const doPreview=async()=>{if(!file)return setMsg('請先選擇檔案。');setBusy(true);setMsg('');try{const form=new FormData();form.append('file',file);const p=await api<Preview>('/admin/master-data/bulk/preview',{method:'POST',body:form},120000);setPreview(p);setResult(null);setMsg(p.errorCount?'仍有錯誤資料，請修正後重新上傳。':'預覽驗證完成。')}catch(e){setPreview(null);setMsg(e instanceof Error?e.message:'預覽失敗')}finally{setBusy(false)}};
 const confirm=async()=>{if(!preview)return;let retro=false;if(preview.requiresRetroactiveConfirmation){if(!window.confirm('此批次包含早於今天生效的回溯異動。確定套用？'))return;retro=true}setBusy(true);try{const r=await api<ConfirmResult>(`/admin/master-data/bulk/${preview.importBatchId}/confirm`,{method:'POST',body:JSON.stringify({confirmRetroactive:retro})},120000);setResult(r);setMsg('主檔批次更新完成。');await onConfirmed()}catch(e){setMsg(e instanceof Error?e.message:'批次更新失敗')}finally{setBusy(false)}};
 return <div className="card" style={{marginTop:18}}><div className="section-title"><div><h2>Excel / CSV 批次設定</h2><div className="sub">完整主檔建議使用 6-sheet Excel；CSV 可一次處理其中一類。上傳只會 Preview，確認後才寫入正式主檔。</div></div><button className="btn small outline" disabled={disabled} onClick={()=>void apiDownload('/admin/master-data/bulk/template.xlsx','UAT主檔設定範本.xlsx')}>下載範本</button></div><div className="actions"><input type="file" accept=".xlsx,.xls,.csv" disabled={disabled} onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setResult(null);setMsg('')}}/><button className="btn secondary" disabled={disabled||!file} onClick={()=>void doPreview()}>預覽與驗證</button></div>{msg&&<div className="note" style={{marginTop:12}}>{msg}</div>}{preview&&<><div className={`note ${preview.errorCount?'danger-note':'ok-note'}`}>共 {preview.totalCount}｜正確 {preview.validCount}｜錯誤 {preview.errorCount}{preview.requiresRetroactiveConfirmation?'｜包含回溯異動':''}</div><div className="table-wrap"><table><thead><tr><th>列</th><th>工作表</th><th>動作</th><th>Key</th><th>結果</th><th>說明</th></tr></thead><tbody>{preview.items.slice(0,200).map((x,i)=><tr key={`${x.sheet}-${x.rowNumber}-${i}`}><td>{x.rowNumber}</td><td>{x.sheet}</td><td>{x.action}{x.isRetroactive?'（回溯）':''}</td><td>{x.displayKey}</td><td>{x.status}</td><td>{x.message||'OK'}</td></tr>)}</tbody></table></div><div className="actions">{preview.errorCount>0&&<button className="btn outline" disabled={disabled} onClick={()=>void apiDownload(`/admin/master-data/bulk/${preview.importBatchId}/errors.xlsx`,'UAT主檔匯入錯誤.xlsx')}>下載錯誤 Excel</button>}<button className="btn ok" disabled={disabled||preview.errorCount>0||!!result} onClick={()=>void confirm()}>確認匯入</button></div></>}{result&&<div className="note ok-note">新增 {result.created}／更新 {result.updated}／無變更 {result.unchanged}／失敗 {result.failed}</div>}</div>
}

function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="table-wrap" style={{marginTop:16}}><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>):<tr><td colSpan={headers.length}>尚無資料</td></tr>}</tbody></table></div>}
