import {useEffect,useMemo,useState} from "react";
import {api} from "../api";
import type {MileageReport} from "../types";
import {downloadCsv,money} from "../utils";

type Props={section:"dashboard"|"locations"|"visitors"|"reports"};
export default function SupervisorPage({section}:Props){
  const today=new Date().toISOString().slice(0,10);
  const [rows,setRows]=useState<MileageReport[]>([]),[start,setStart]=useState("2026-01-01"),[end,setEnd]=useState(today),[msg,setMsg]=useState(""),[locationKeyword,setLocationKeyword]=useState(""),[visitor,setVisitor]=useState("");
  const load=()=>api<MileageReport[]>(`/reports/mileage?startDate=${start}&endDate=${end}`).then(setRows).catch(e=>setMsg(e.message));
  useEffect(()=>{void load()},[section]);
  const approved=rows.filter(x=>x.status==="Approved");
  const visitors=useMemo(()=>[...new Set(rows.map(x=>x.visitorName))].sort((a,b)=>a.localeCompare(b,"zh-Hant")),[rows]);
  const locationRows=useMemo(()=>rows.filter(x=>!locationKeyword||x.route.toLowerCase().includes(locationKeyword.toLowerCase())),[rows,locationKeyword]);
  const visitorRows=useMemo(()=>rows.filter(x=>!visitor||x.visitorName===visitor),[rows,visitor]);
  const download=(name:string,data:MileageReport[])=>downloadCsv(`${name}.csv`,data.map(x=>({日期:x.visitDate,外訪員:x.visitorName,小組:x.teamName||"",路線:x.route,外訪員自算:x.claimedDistanceKm??"",系統里程:x.systemDistanceKm??"",核定里程:x.approvedDistanceKm??"",每公里補助:x.ratePerKmSnapshot??"",補助金額:x.approvedAmount??"",狀態:x.statusName})));

  if(section==="dashboard")return <><div className="grid cols-4"><div className="card stat"><div className="label">可查詢行程</div><div className="value">{rows.length}</div><div className="hint">目前日期範圍</div></div><div className="card stat"><div className="label">已核准紀錄</div><div className="value">{approved.length}</div><div className="hint">唯讀</div></div><div className="card stat"><div className="label">核定里程</div><div className="value">{approved.reduce((s,x)=>s+(x.approvedDistanceKm||0),0).toFixed(1)}</div><div className="hint">公里</div></div><div className="card stat"><div className="label">補助金額</div><div className="value">${money(approved.reduce((s,x)=>s+(x.approvedAmount||0),0))}</div><div className="hint">依核准快照加總</div></div></div><div className="card" style={{marginTop:18}}><div className="section-title"><h2>督導查詢權限</h2><span className="pill">唯讀</span></div><div className="note">可以查詢及下載地點拜訪狀況、外訪員行程與整體彙總報表；不得新增、修改、核准、退回、維護地點或管理帳號。</div></div></>;

  const dateFilters=<div className="grid cols-4"><div className="field"><label>開始日期</label><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>結束日期</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div>;

  if(section==="locations")return <div className="card"><div className="section-title"><h2>地點拜訪狀況</h2><button className="btn secondary" onClick={()=>download("地點拜訪狀況",locationRows)}>下載</button></div>{dateFilters}<div className="grid cols-2"><div className="field"><label>地點關鍵字</label><input value={locationKeyword} onChange={e=>setLocationKeyword(e.target.value)} placeholder="客戶名稱、地址或路線關鍵字"/></div><div className="field"><label>&nbsp;</label><button className="btn" onClick={load}>查詢日期</button></div></div>{msg&&<div className="note danger-note">{msg}</div>}<div className="table-wrap"><table><thead><tr><th>日期</th><th>路線／地點</th><th>外訪員</th><th>小組</th><th>核定里程</th><th>每公里補助</th><th>補助金額</th></tr></thead><tbody>{locationRows.map(x=><tr key={x.tripNo}><td>{x.visitDate}</td><td>{x.route}</td><td>{x.visitorName}</td><td>{x.teamName||"—"}</td><td>{x.approvedDistanceKm??"—"}</td><td>{x.ratePerKmSnapshot==null?"—":`$${money(x.ratePerKmSnapshot)}`}</td><td className="subsidy-strong">{x.approvedAmount==null?"—":`$${money(x.approvedAmount)}`}</td></tr>)}</tbody></table></div></div>;

  if(section==="visitors")return <div className="card"><div className="section-title"><h2>外訪員行程</h2><button className="btn secondary" onClick={()=>download("外訪員行程",visitorRows)}>下載</button></div>{dateFilters}<div className="grid cols-2"><div className="field"><label>外訪員</label><select value={visitor} onChange={e=>setVisitor(e.target.value)}><option value="">全部外訪員</option>{visitors.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>&nbsp;</label><button className="btn" onClick={load}>查詢日期</button></div></div><div className="table-wrap"><table><thead><tr><th>日期</th><th>外訪員</th><th>小組</th><th>拜訪順序</th><th>自算</th><th>系統</th><th>核定</th><th>每公里補助</th><th>補助金額</th><th>狀態</th></tr></thead><tbody>{visitorRows.map(x=><tr key={x.tripNo}><td>{x.visitDate}</td><td>{x.visitorName}</td><td>{x.teamName||"—"}</td><td>{x.route}</td><td>{x.claimedDistanceKm??"—"}</td><td>{x.systemDistanceKm??"—"}</td><td>{x.approvedDistanceKm??"—"}</td><td>{x.ratePerKmSnapshot==null?"—":`$${money(x.ratePerKmSnapshot)}`}</td><td className="subsidy-strong">{x.approvedAmount==null?"—":`$${money(x.approvedAmount)}`}</td><td>{x.statusName}</td></tr>)}</tbody></table></div></div>;

  return <><div className="grid cols-3">{[["每日行程明細","完整行程與補助"],["里程彙總報表","三種里程與補助金額"],["地點使用分析","路線／地點與補助"]].map(([n,d])=><div className="card report-card" key={n}><h2>{n}</h2><p>{d}</p><button className="btn small secondary" onClick={()=>download(n,rows)}>下載</button></div>)}</div><div className="card" style={{marginTop:18}}><div className="section-title"><h2>整體報表查詢</h2><span className="pill">唯讀</span></div>{dateFilters}<button className="btn" onClick={load}>查詢</button><div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>日期</th><th>外訪員</th><th>小組</th><th>路線</th><th>核定里程</th><th>每公里補助</th><th>補助金額</th><th>狀態</th></tr></thead><tbody>{rows.map(x=><tr key={x.tripNo}><td>{x.visitDate}</td><td>{x.visitorName}</td><td>{x.teamName||"—"}</td><td>{x.route}</td><td>{x.approvedDistanceKm??"—"}</td><td>{x.ratePerKmSnapshot==null?"—":`$${money(x.ratePerKmSnapshot)}`}</td><td className="subsidy-strong">{x.approvedAmount==null?"—":`$${money(x.approvedAmount)}`}</td><td>{x.statusName}</td></tr>)}</tbody></table></div></div></>;
}
