import{useEffect,useMemo,useState}from"react";
import{useNavigate}from"react-router-dom";
import{api,apiDownload}from"../api";
import{useAuth}from"../auth";
import type{CorrectionDraft,CorrectionProposal,PagedResult,Project,Team,TripQueryRow,UserOption,VisitType}from"../types";
import{km,money,monthStart,previousMonthRange,qs,threeMonthStart,todayTaipei}from"../v160";

type Props={title?:string;allowCorrection?:boolean};
const statuses=[['','全部狀態'],['Draft','草稿'],['Submitted','已送出'],['RoutePending','待計算里程'],['PendingApproval','待核准'],['Approved','已核准'],['Returned','已退回']];

export default function UnifiedQueryPage({title="行程查詢",allowCorrection=false}:Props){
 const{user}=useAuth();const navigate=useNavigate();const today=todayTaipei();
 const[start,setStart]=useState(monthStart(today)),[end,setEnd]=useState(today),[teamId,setTeamId]=useState(''),[visitorId,setVisitorId]=useState(''),[locationKeyword,setLocationKeyword]=useState(''),[projectId,setProjectId]=useState(''),[visitTypeId,setVisitTypeId]=useState(''),[status,setStatus]=useState(''),[includeCancelled,setIncludeCancelled]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(50);
 const[rows,setRows]=useState<PagedResult<TripQueryRow>>({items:[],page:1,pageSize:50,totalCount:0,totalPages:0}),[teams,setTeams]=useState<Team[]>([]),[visitors,setVisitors]=useState<UserOption[]>([]),[projects,setProjects]=useState<Project[]>([]),[visitTypes,setVisitTypes]=useState<VisitType[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState<TripQueryRow|null>(null),[correction,setCorrection]=useState<CorrectionDraft|null>(null),[reason,setReason]=useState(''),[applied,setApplied]=useState<Record<string,unknown>|null>(null);
 const activeRole=(sessionStorage.getItem('fieldvisit_active_role')||user?.roles[0]||'visitor').toLowerCase();
 const canCrossTeam=['leader','admin','supervisor'].includes(activeRole);
 const canIncludeCancelled=activeRole==='admin';

 useEffect(()=>{Promise.all([api<Team[]>('/teams'),api<UserOption[]>('/query/visitors'),api<Project[]>('/projects'),api<VisitType[]>('/visit-types')]).then(([t,u,p,v])=>{setTeams(t);setVisitors(u);setProjects(p);setVisitTypes(v)}).catch(e=>setMsg(e.message))},[]);
 const currentParams=(p=page,overridePageSize=pageSize)=>({startDate:start,endDate:end,teamId:teamId||undefined,visitorId:visitorId||undefined,locationKeyword:locationKeyword||undefined,projectId:projectId||undefined,visitTypeId:visitTypeId||undefined,status:status||undefined,includeCancelled:canIncludeCancelled?includeCancelled:false,page:p,pageSize:overridePageSize});
 const load=async(p=1,overridePageSize=pageSize)=>{setBusy(true);setMsg('');try{const request=currentParams(p,overridePageSize);const r=await api<PagedResult<TripQueryRow>>(`/query/trips?${qs(request)}`);setRows(r);setPage(r.page);setApplied({...request,page:1})}catch(e){setMsg(e instanceof Error?e.message:'查詢失敗')}finally{setBusy(false)}};
 useEffect(()=>{void load(1)},[]);
 const appliedDescription=useMemo(()=>`${String(applied?.startDate||start)}～${String(applied?.endDate||end)}｜${rows.totalCount} 筆`,[applied,start,end,rows.totalCount]);
 const quick=(kind:'month'|'prev'|'3m')=>{if(kind==='month'){setStart(monthStart(today));setEnd(today)}else if(kind==='prev'){const r=previousMonthRange();setStart(r.start);setEnd(r.end)}else{setStart(threeMonthStart());setEnd(today)}};
 const download=async(format:'xlsx'|'pdf')=>{if(!applied)return setMsg('請先執行查詢，再下載目前查詢結果。');setBusy(true);setMsg('');try{await apiDownload(`/query/trips/export.${format}?${qs({...applied,page:1,pageSize:100})}`,`外訪行程查詢.${format}`)}catch(e){setMsg(e instanceof Error?e.message:'下載失敗')}finally{setBusy(false)}};
 const startCorrection=async(row:TripQueryRow)=>{setMsg('');try{setCorrection(await api<CorrectionDraft>(`/corrections/draft/${row.visitTripId}`));setReason('')}catch(e){setMsg(e instanceof Error?e.message:'無法開啟更正申請')}};
 const updateProposal=(patch:Partial<CorrectionProposal>)=>setCorrection(c=>c?{...c,proposal:{...c.proposal,...patch}}:c);
 const updateStop=(index:number,patch:Partial<CorrectionProposal['stops'][number]>)=>setCorrection(c=>c?{...c,proposal:{...c.proposal,stops:c.proposal.stops.map((s,i)=>i===index?{...s,...patch}:s)}}:c);
 const submitCorrection=async()=>{if(!correction||!reason.trim())return setMsg('請填寫更正原因。');setBusy(true);try{await api('/corrections',{method:'POST',body:JSON.stringify({visitTripId:correction.visitTripId,reason:reason.trim(),proposal:correction.proposal})});setCorrection(null);setMsg('更正申請已送出，等待小組長審核。');await load(page)}catch(e){setMsg(e instanceof Error?e.message:'更正申請失敗')}finally{setBusy(false)}};

 return <>
  <div className="card">
   <div className="section-title"><div><h2>{title}</h2><div className="sub">同一套查詢條件同時套用畫面、Excel 與 PDF；下載包含全部符合資料，不受分頁限制。</div></div><div className="actions"><button className="btn secondary" onClick={()=>void download('xlsx')} disabled={busy}>下載 Excel</button><button className="btn secondary" onClick={()=>void download('pdf')} disabled={busy}>下載 PDF</button></div></div>
   <div className="quick-filters"><button className="btn small outline" onClick={()=>quick('month')}>本月</button><button className="btn small outline" onClick={()=>quick('prev')}>上月</button><button className="btn small outline" onClick={()=>quick('3m')}>近 3 個月</button></div>
   <div className="grid cols-4 query-grid">
    <div className="field"><label>開始日期</label><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>結束日期</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>
    {canCrossTeam&&<div className="field"><label>小組</label><select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">全部授權小組</option>{teams.map(t=><option key={t.teamId} value={t.teamId}>{t.teamName}</option>)}</select></div>}
    {canCrossTeam&&<div className="field"><label>外訪員</label><select value={visitorId} onChange={e=>setVisitorId(e.target.value)}><option value="">全部外訪員</option>{visitors.filter(v=>!teamId||String(v.teamId)===teamId).map(v=><option key={v.userId} value={v.userId}>{v.displayName}｜{v.employeeNo}</option>)}</select></div>}
    <div className="field"><label>地點關鍵字</label><input value={locationKeyword} onChange={e=>setLocationKeyword(e.target.value)} placeholder="地點名稱、地址或地點代碼"/></div>
    <div className="field"><label>專案</label><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">全部專案</option>{projects.map(p=><option key={p.projectId} value={p.projectId}>{p.projectName}</option>)}</select></div>
    <div className="field"><label>拜訪形式</label><select value={visitTypeId} onChange={e=>setVisitTypeId(e.target.value)}><option value="">全部拜訪形式</option>{visitTypes.map(v=><option key={v.visitTypeId} value={v.visitTypeId}>{v.visitTypeName}</option>)}</select></div>
    <div className="field"><label>狀態</label><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div>
   </div>
   <div className="actions query-actions"><button className="btn" onClick={()=>void load(1)} disabled={busy}>查詢</button><button className="btn outline" onClick={()=>{setTeamId('');setVisitorId('');setLocationKeyword('');setProjectId('');setVisitTypeId('');setStatus('');setIncludeCancelled(false);setStart(monthStart(today));setEnd(today)}}>清除條件</button>{canIncludeCancelled&&<label className="check-row"><input type="checkbox" checked={includeCancelled} onChange={e=>setIncludeCancelled(e.target.checked)}/>包含已作廢</label>}</div>
   {msg&&<div className="note" style={{marginTop:12}}>{msg}</div>}
   <div className="query-result-head"><strong>查詢結果</strong><span>{appliedDescription}</span><label>每頁 <select value={pageSize} onChange={e=>{const n=Number(e.target.value);setPageSize(n);void load(1,n)}}><option>20</option><option>50</option><option>100</option></select></label></div>
   <div className="table-wrap"><table><thead><tr><th>日期</th><th>外訪員</th><th>小組</th><th>專案</th><th>路線</th><th>自算</th><th>系統</th><th>核定</th><th>費率</th><th>補助</th><th>狀態</th><th>操作</th></tr></thead><tbody>{rows.items.map(r=><tr key={r.visitTripId}><td>{r.visitDate}</td><td>{r.visitorName}</td><td>{r.teamName||'—'}</td><td>{r.projectNames||'—'}</td><td>{r.route}</td><td>{km(r.claimedDistanceKm)}</td><td>{km(r.systemDistanceKm)}</td><td>{km(r.approvedDistanceKm)}</td><td>{money(r.ratePerKmSnapshot)}</td><td>{money(r.subsidyAmount)}</td><td><span className={`pill ${r.status==='Approved'?'ok':r.status==='Returned'?'danger':'warn'}`}>{r.statusName}</span>{r.snapshotVersion>0&&<div className="muted">Snapshot V{r.snapshotVersion}</div>}{r.status==='Returned'&&r.returnReason&&<div className="muted"><strong>退回原因：</strong>{r.returnReason}</div>}</td><td><div className="actions">{allowCorrection&&(r.status==='Draft'||r.status==='Returned')&&<button className="btn small secondary" onClick={()=>navigate(`/?edit=${r.visitTripId}`)}>{r.status==='Returned'?'修改後重送':'繼續編輯／送出'}</button>}<button className="btn small outline" onClick={()=>setDetail(r)}>查看</button>{allowCorrection&&r.status==='Approved'&&<button className="btn small secondary" onClick={()=>void startCorrection(r)}>申請更正</button>}</div></td></tr>)}</tbody></table></div>
   {!rows.items.length&&<div className="empty">查無符合條件的資料。</div>}
   <div className="pager"><button className="btn small outline" disabled={page<=1||busy} onClick={()=>void load(page-1)}>上一頁</button><span>第 {rows.page} / {Math.max(rows.totalPages,1)} 頁，共 {rows.totalCount} 筆</span><button className="btn small outline" disabled={page>=rows.totalPages||busy} onClick={()=>void load(page+1)}>下一頁</button></div>
  </div>

  {detail&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><div className="modal-panel"><h3>{detail.tripNo}</h3><div className="note">{detail.visitDate}｜{detail.visitorName}｜{detail.teamName||'—'}｜{detail.statusName}</div>{detail.status==='Returned'&&detail.returnReason&&<div className="note danger-note" style={{marginTop:10}}><strong>主管退回原因：</strong>{detail.returnReason}</div>}<p><strong>路線：</strong>{detail.route}</p><div className="route-list">{detail.stops.map(s=><div className="route-item" key={s.stopSequence}><div className="route-index">{s.stopSequence}</div><div><div className="route-name">{s.locationCode?`${s.locationCode}｜`:''}{s.locationName}</div><div className="route-address">{s.address||'—'}</div><div className="muted">{s.projectName||'非專案'}｜{s.visitTypeName||'未指定拜訪形式'}｜目的：{s.visitPurpose||'未填'}</div></div></div>)}</div><p><strong>里程：</strong>自算 {km(detail.claimedDistanceKm)}／系統 {km(detail.systemDistanceKm)}／核定 {km(detail.approvedDistanceKm)}<br/><strong>補助：</strong>{money(detail.ratePerKmSnapshot)}／km，合計 {money(detail.subsidyAmount)}</p><div className="actions">{allowCorrection&&(detail.status==='Draft'||detail.status==='Returned')&&<button className="btn ok" onClick={()=>{const id=detail.visitTripId;setDetail(null);navigate(`/?edit=${id}`)}}>{detail.status==='Returned'?'修改後重送':'繼續編輯／送出'}</button>}<button className="btn" onClick={()=>setDetail(null)}>關閉</button></div></div></div>}

  {correction&&<div className="modal"><div className="modal-panel correction-modal"><h3>申請更正｜{correction.tripNo}</h3><div className="note">更正不會覆寫原核准資料；核准後會建立新的 Snapshot 版本。</div><div className="field"><label>更正原因</label><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="請說明錯誤原因與需要更正的內容"/></div><div className="grid cols-3"><div className="field"><label>日期</label><input type="date" value={correction.proposal.visitDate} onChange={e=>updateProposal({visitDate:e.target.value})}/></div><div className="field"><label>開始時間</label><input type="time" value={(correction.proposal.startTime||'').slice(0,5)} onChange={e=>updateProposal({startTime:e.target.value?`${e.target.value}:00`:undefined})}/></div><div className="field"><label>結束時間</label><input type="time" value={(correction.proposal.endTime||'').slice(0,5)} onChange={e=>updateProposal({endTime:e.target.value?`${e.target.value}:00`:undefined})}/></div><div className="field"><label>外訪員自算里程</label><input type="number" step="0.1" value={correction.proposal.claimedDistanceKm??''} onChange={e=>updateProposal({claimedDistanceKm:e.target.value?Number(e.target.value):undefined})}/></div><div className="field"><label>申請更正核定里程</label><input type="number" step="0.1" value={correction.proposal.approvedDistanceKm??''} onChange={e=>updateProposal({approvedDistanceKm:e.target.value?Number(e.target.value):undefined})}/></div></div><div className="field"><label>備註</label><textarea value={correction.proposal.notes||''} onChange={e=>updateProposal({notes:e.target.value})}/></div><h4>拜訪地點</h4>{correction.proposal.stops.map((s,i)=><div className="correction-stop" key={i}><strong>#{s.stopSequence}</strong><div className="grid cols-2"><div className="field"><label>地點名稱</label><input value={s.locationName} onChange={e=>updateStop(i,{locationName:e.target.value})}/></div><div className="field"><label>地址</label><input value={s.address||''} onChange={e=>updateStop(i,{address:e.target.value})}/></div><div className="field"><label>專案名稱</label><input value={s.projectName||''} onChange={e=>updateStop(i,{projectName:e.target.value})}/></div><div className="field"><label>拜訪形式</label><input value={s.visitTypeName||''} onChange={e=>updateStop(i,{visitTypeName:e.target.value})}/></div><div className="field span-2"><label>行程目的</label><input value={s.visitPurpose||''} onChange={e=>updateStop(i,{visitPurpose:e.target.value})}/></div></div></div>)}<div className="modal-sticky-actions"><button className="btn secondary" onClick={()=>setCorrection(null)}>取消</button><button className="btn ok" onClick={()=>void submitCorrection()} disabled={busy}>送出更正申請</button></div></div></div>}
 </>
}
