import {useEffect,useState} from "react";import {useSearchParams} from "react-router-dom";import {api} from "../api";import type {Location,Project,Trip,TripStopInput,VisitType} from "../types";
export default function VisitorPage(){const today=new Date().toISOString().slice(0,10);const [sp,setSp]=useSearchParams();const editId=sp.get("edit");
 const [date,setDate]=useState(today),[start,setStart]=useState("08:30"),[end,setEnd]=useState("17:00"),[km,setKm]=useState("30"),[purpose,setPurpose]=useState(""),[notes,setNotes]=useState(""),[locations,setLocations]=useState<Location[]>([]),[projects,setProjects]=useState<Project[]>([]),[visitTypes,setVisitTypes]=useState<VisitType[]>([]),[stops,setStops]=useState<TripStopInput[]>([]),[locId,setLocId]=useState(""),[projectId,setProjectId]=useState(""),[projectLocs,setProjectLocs]=useState<Location[]>([]),[projectLocId,setProjectLocId]=useState(""),[visitTypeId,setVisitTypeId]=useState(""),[rowVersion,setRowVersion]=useState(""),[overlap,setOverlap]=useState(false),[confirmOverlap,setConfirmOverlap]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([api<Location[]>("/locations"),api<Project[]>("/projects"),api<VisitType[]>("/visit-types")]).then(([l,p,v])=>{setLocations(l);setProjects(p);setVisitTypes(v);setLocId(String(l[0]?.locationId||""));setProjectId(String(p[0]?.projectId||""));setVisitTypeId(String(v[0]?.visitTypeId||""));}).catch(e=>setMsg(e.message))},[]);
 useEffect(()=>{if(!projectId)return;const p=projects.find(x=>x.projectId===Number(projectId));if(p?.locationMode==="List")api<Location[]>(`/projects/${projectId}/locations`).then(r=>{setProjectLocs(r);setProjectLocId(String(r[0]?.locationId||""));}).catch(e=>setMsg(e.message));else setProjectLocs([])},[projectId,projects]);
 useEffect(()=>{if(!editId)return;api<Trip>(`/trips/${editId}`).then(t=>{setDate(t.visitDate);setStart((t.startTime||"").slice(0,5));setEnd((t.endTime||"").slice(0,5));setKm(String(t.claimedDistanceKm||""));setPurpose(t.purpose||"");setNotes(t.notes||"");setStops(t.stops);setRowVersion(t.rowVersion);setMsg(`已載入 ${t.tripNo}，修改後可重新送出。`)}).catch(e=>setMsg(e.message))},[editId]);
 useEffect(()=>{const timer=setTimeout(()=>{if(!date||!start||!end||end<=start)return;api<{hasOverlap:boolean;message?:string}>("/trips/time-overlap-check",{method:"POST",body:JSON.stringify({visitDate:date,startTime:start,endTime:end,excludeVisitTripId:editId?Number(editId):null})}).then(r=>{setOverlap(r.hasOverlap);if(!r.hasOverlap)setConfirmOverlap(false)}).catch(()=>{})},400);return()=>clearTimeout(timer)},[date,start,end,editId]);
 const addMaster=()=>{const l=locations.find(x=>x.locationId===Number(locId));if(!l)return;setStops(s=>[...s,{locationId:l.locationId,sourceType:"Master",locationName:l.locationName,address:l.address}])};
 const addProject=()=>{const p=projects.find(x=>x.projectId===Number(projectId));const vt=visitTypes.find(x=>x.visitTypeId===Number(visitTypeId));if(!p||!vt)return;if(p.locationMode==="List"){const l=projectLocs.find(x=>x.locationId===Number(projectLocId));if(!l)return;setStops(s=>[...s,{locationId:l.locationId,projectId:p.projectId,visitTypeId:vt.visitTypeId,sourceType:"ProjectList",locationName:l.locationName,address:l.address,visitPurpose:vt.visitTypeName}]);}else{const name=prompt("專案地點名稱");const address=prompt("地址或 Plus Code");if(name&&address)setStops(s=>[...s,{projectId:p.projectId,visitTypeId:vt.visitTypeId,sourceType:"Temporary",locationName:name,address,visitPurpose:vt.visitTypeName}])}};
 const addTemp=()=>{const name=prompt("臨時公務地點名稱");const address=prompt("地址或 Plus Code");if(name&&address)setStops(s=>[...s,{sourceType:"Temporary",locationName:name,address}])};
 const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=stops.length)return;const c=[...stops];[c[i],c[j]]=[c[j],c[i]];setStops(c)};
 const reset=()=>{setSp({});setDate(today);setStart("08:30");setEnd("17:00");setKm("30");setPurpose("");setNotes("");setStops([]);setRowVersion("");setOverlap(false);setConfirmOverlap(false)};
 const save=async(submit:boolean)=>{if(stops.length<2)return setMsg("至少需要兩個公務地點。");if(overlap&&!confirmOverlap)return setMsg("請先確認時間重疊提醒。");setBusy(true);try{const body={visitDate:date,startTime:start,endTime:end,claimedDistanceKm:Number(km),purpose,notes,timeOverlapConfirmed:confirmOverlap,stops};let t:Trip;if(editId){t=await api<Trip>(`/trips/${editId}`,{method:"PUT",headers:{"If-Match":rowVersion},body:JSON.stringify(body)})}else{t=await api<Trip>("/trips",{method:"POST",body:JSON.stringify(body)})}setRowVersion(t.rowVersion);if(submit){const sent=await api<Trip>(`/trips/${t.visitTripId}/submit`,{method:"POST",headers:{"If-Match":t.rowVersion},body:JSON.stringify({confirmTimeOverlap:confirmOverlap})});setMsg(`已送出 ${sent.tripNo}，小組長可在另一台裝置看到。`);reset()}else{setSp({edit:String(t.visitTripId)});setMsg(`草稿已儲存 ${t.tripNo}`)}}catch(e){setMsg(e instanceof Error?e.message:"儲存失敗")}finally{setBusy(false)}};
 return <><div className="stats"><div className="card"><span>日期</span><b>{date}</b></div><div className="card"><span>地點</span><b>{stops.length}</b></div><div className="card"><span>自算里程</span><b>{km} km</b></div><div className="card"><span>模式</span><b>{editId?"修改/重送":"新增"}</b></div></div><div className="card"><h2>基本資料</h2><div className="grid two"><label>日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>自算里程 km<input type="number" min="0" step="0.1" value={km} onChange={e=>setKm(e.target.value)}/></label><label>出發<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>結束<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>{overlap&&<div className="alert danger">時間與既有紀錄重疊，請確認時間是否正確。<label className="check"><input type="checkbox" checked={confirmOverlap} onChange={e=>setConfirmOverlap(e.target.checked)}/>我確認時間正確，仍要送出</label></div>}</div>
 <div className="card"><h2>從正式地點加入</h2><div className="inline"><select value={locId} onChange={e=>setLocId(e.target.value)}>{locations.map(l=><option key={l.locationId} value={l.locationId}>{l.city}/{l.district}｜{l.locationName}</option>)}</select><button className="btn" onClick={addMaster}>加入</button><button className="btn secondary" onClick={addTemp}>＋臨時地點</button></div></div>
 <div className="card"><h2>從專案加入</h2><div className="grid three"><label>專案<select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.projectId} value={p.projectId}>{p.projectName}</option>)}</select></label><label>拜訪形式<select value={visitTypeId} onChange={e=>setVisitTypeId(e.target.value)}>{visitTypes.map(v=><option key={v.visitTypeId} value={v.visitTypeId}>{v.visitTypeName}</option>)}</select></label>{projects.find(p=>p.projectId===Number(projectId))?.locationMode==="List"&&<label>專案地點<select value={projectLocId} onChange={e=>setProjectLocId(e.target.value)}>{projectLocs.map(l=><option key={l.locationId} value={l.locationId}>{l.locationName}</option>)}</select></label>}</div><button className="btn secondary" onClick={addProject}>加入專案地點</button></div>
 <div className="card"><h2>拜訪順序</h2><div className="route">{stops.map((s,i)=><div className="stop" key={`${s.locationId||s.locationName}-${i}`}><b>{i+1}</b><div><strong>{s.locationName}</strong><small>{s.address}</small></div><div className="actions"><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button onClick={()=>setStops(stops.filter((_,x)=>x!==i))}>×</button></div></div>)}</div></div>
 <div className="card"><div className="grid two"><label>行程目的<input value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label>備註<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{msg&&<div className="alert">{msg}</div>}<div className="actions"><button className="btn secondary" disabled={busy} onClick={()=>void save(false)}>儲存草稿</button><button className="btn ok" disabled={busy} onClick={()=>void save(true)}>{editId?"重新送出":"送出行程"}</button>{editId&&<button className="btn ghost" onClick={reset}>取消修改</button>}</div></div></>}
